import { createFactorRegistryRelease } from '@/domain/model/definitions/registry';
import type {
  ActionDefinition,
  DimensionDefinition,
  DomainDefinition,
  FactorDefinition,
  FactorDisplayKeys,
  InstrumentDefinition,
  MeasurementDefinition,
  UnhashedFactorRegistryRelease,
} from '@/domain/model/definitions/definitionTypes';

export const MVP_DOMAINS: readonly DomainDefinition[] = [
  {
    id: 'domain.communication',
    key: 'communication',
    title: 'Общение',
    description: 'Навыки разговора, восстановления контакта и совместного понимания.',
    order: 10,
    version: 1,
  },
  {
    id: 'domain.wellbeing',
    key: 'wellbeing',
    title: 'Текущее состояние',
    description: 'Временные состояния, которые влияют на доступный ресурс.',
    order: 20,
    version: 1,
  },
  {
    id: 'domain.sharedLife',
    key: 'sharedLife',
    title: 'Совместная жизнь',
    description: 'Предпочтения, роли и координация повседневной жизни.',
    order: 30,
    version: 1,
  },
  {
    id: 'domain.lifePlans',
    key: 'lifePlans',
    title: 'Жизненные планы',
    description: 'Значимые планы и некомпенсируемые ограничения.',
    order: 40,
    version: 1,
  },
];

export const MVP_DIMENSIONS_V6: readonly DimensionDefinition[] = [
  {
    id: 'dimension.communicationConflict',
    key: 'communication.conflict',
    domainKey: 'communication',
    title: 'Разговор после напряжения',
    description: 'Способность остановить эскалацию и вернуться к разговору.',
    order: 10,
    version: 1,
  },
  {
    id: 'dimension.communicationWeekly',
    key: 'communication.weekly',
    domainKey: 'communication',
    title: 'Недельный контакт',
    description: 'Субъективное состояние контакта и напряжения на этой неделе.',
    order: 20,
    version: 1,
  },
  {
    id: 'dimension.wellbeingCurrent',
    key: 'wellbeing.current',
    domainKey: 'wellbeing',
    title: 'Текущий ресурс',
    description: 'Перегрузка и доступная энергия в текущем периоде.',
    order: 10,
    version: 1,
  },
  {
    id: 'dimension.sharedLifePlanning',
    key: 'sharedLife.planning',
    domainKey: 'sharedLife',
    title: 'Планирование',
    description: 'Комфортный баланс спонтанности и заранее заданной структуры.',
    order: 10,
    version: 1,
  },
  {
    id: 'dimension.sharedLifeRoles',
    key: 'sharedLife.roles',
    domainKey: 'sharedLife',
    title: 'Бытовые роли',
    description: 'Способность и готовность покрывать роли совместной жизни.',
    order: 20,
    version: 1,
  },
  {
    id: 'dimension.lifePlansFamily',
    key: 'lifePlans.family',
    domainKey: 'lifePlans',
    title: 'Планы о семье',
    description: 'Принципиальные ожидания о будущем семьи.',
    order: 10,
    version: 1,
  },
];

const masterySchema = {
  type: 'MASTERY',
  basicMaxExclusive: 0.4,
  intermediateMaxExclusive: 0.75,
} as const;

const displayKeysFor = (factorKey: string): FactorDisplayKeys => ({
  titleKey: `factor.${factorKey}.title`,
  descriptionKey: `factor.${factorKey}.description`,
  explanationKey: `factor.${factorKey}.explanation`,
});

const weeklyStateConfidence = {
  minimumEvidenceReliability: 0.25,
  minimumSnapshotConfidence: 0.2,
  minimumPairConfidence: 0.35,
} as const;

const weeklyStateFreshness = {
  type: 'DECAY',
  halfLifeDays: 7,
  expiresAfterDays: 28,
} as const;

export const MVP_FACTORS_V6: readonly FactorDefinition[] = [
  {
    id: 'factor.communicationConflictRepairSkill',
    key: 'communication.conflict.repairSkill',
    domainKey: 'communication',
    dimensionKey: 'communication.conflict',
    title: 'Навык восстановления разговора',
    description: 'Умение остановить эскалацию, взять паузу и вернуться к разговору.',
    type: 'SKILL',
    valueSchema: masterySchema,
    semantics: {
      kind: 'ORDERED',
      lowPole: { key: 'needs_support', label: 'нужна поддержка' },
      highPole: { key: 'independent_repair', label: 'самостоятельное восстановление' },
      labels: [
        { key: 'BASIC', label: 'базовый навык' },
        { key: 'INTERMEDIATE', label: 'устойчивый навык' },
        { key: 'ADVANCED', label: 'развитый навык' },
      ],
      interpretation: 'CAPABILITY',
    },
    aggregationStrategy: {
      type: 'RECENCY_WEIGHTED',
      minimumEvidence: 2,
      expectedEvidence: 4,
      halfLifeDays: 90,
    },
    developmentPolicy: 'TRAINABLE',
    pairStrategies: [
      {
        strategyVersion: 2,
        directionality: 'SYMMETRIC',
        context: 'COMMITTED_RELATIONSHIP',
        config: { type: 'MINIMUM_BOTH', minimum: 0.4 },
        minimumConfidence: 0.35,
        actionability: 'SKILL_BUILDING',
      },
    ],
    privacyClass: 'NORMAL',
    contexts: ['SELF', 'DATING', 'COMMITTED_RELATIONSHIP'],
    confidenceRequirements: {
      minimumEvidenceReliability: 0.25,
      minimumSnapshotConfidence: 0.25,
      minimumPairConfidence: 0.35,
    },
    freshnessPolicy: {
      type: 'DECAY',
      halfLifeDays: 90,
      expiresAfterDays: 365,
    },
    displayKeys: displayKeysFor('communication.conflict.repairSkill'),
    definitionVersion: 2,
  },
  {
    id: 'factor.communicationWeeklyConnection',
    key: 'communication.weekly.connection',
    domainKey: 'communication',
    dimensionKey: 'communication.weekly',
    title: 'Ощущение контакта',
    description: 'Текущее субъективное ощущение контакта в отношениях.',
    type: 'STATE',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    semantics: {
      kind: 'ORDERED',
      lowPole: { key: 'low_connection', label: 'мало ощущения контакта' },
      highPole: { key: 'high_connection', label: 'много ощущения контакта' },
      labels: [],
      interpretation: 'CONNECTION',
    },
    aggregationStrategy: {
      type: 'RECENCY_WEIGHTED',
      minimumEvidence: 1,
      expectedEvidence: 3,
      halfLifeDays: 7,
    },
    developmentPolicy: 'STATE_MANAGEMENT',
    pairStrategies: [
      {
        strategyVersion: 2,
        directionality: 'SYMMETRIC',
        context: 'COMMITTED_RELATIONSHIP',
        config: { type: 'MINIMUM_BOTH', minimum: 0.35 },
        minimumConfidence: 0.35,
        actionability: 'AWARENESS',
      },
    ],
    privacyClass: 'PRIVATE',
    contexts: ['SELF', 'COMMITTED_RELATIONSHIP'],
    confidenceRequirements: weeklyStateConfidence,
    freshnessPolicy: weeklyStateFreshness,
    displayKeys: displayKeysFor('communication.weekly.connection'),
    definitionVersion: 3,
  },
  {
    id: 'factor.communicationWeeklyTension',
    key: 'communication.weekly.tension',
    domainKey: 'communication',
    dimensionKey: 'communication.weekly',
    title: 'Текущее напряжение',
    description: 'Субъективная интенсивность напряжения в текущем периоде.',
    type: 'STATE',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    semantics: {
      kind: 'ORDERED',
      lowPole: { key: 'low_tension', label: 'мало напряжения' },
      highPole: { key: 'high_tension', label: 'много напряжения' },
      labels: [],
      interpretation: 'STATE_INTENSITY',
    },
    aggregationStrategy: {
      type: 'RECENCY_WEIGHTED',
      minimumEvidence: 1,
      expectedEvidence: 3,
      halfLifeDays: 7,
    },
    developmentPolicy: 'STATE_MANAGEMENT',
    pairStrategies: [
      {
        strategyVersion: 2,
        directionality: 'SYMMETRIC',
        context: 'COMMITTED_RELATIONSHIP',
        config: { type: 'TARGET_RANGE', targetMin: 0, targetMax: 0.65 },
        minimumConfidence: 0.35,
        actionability: 'AWARENESS',
      },
    ],
    privacyClass: 'SENSITIVE',
    contexts: ['SELF', 'COMMITTED_RELATIONSHIP'],
    confidenceRequirements: weeklyStateConfidence,
    freshnessPolicy: weeklyStateFreshness,
    displayKeys: displayKeysFor('communication.weekly.tension'),
    definitionVersion: 3,
  },
  {
    id: 'factor.wellbeingCurrentOverload',
    key: 'wellbeing.current.overload',
    domainKey: 'wellbeing',
    dimensionKey: 'wellbeing.current',
    title: 'Текущая перегрузка',
    description: 'Временное ощущение перегрузки, а не устойчивая черта человека.',
    type: 'STATE',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    semantics: {
      kind: 'ORDERED',
      lowPole: { key: 'low_overload', label: 'низкая перегрузка' },
      highPole: { key: 'high_overload', label: 'высокая перегрузка' },
      labels: [],
      interpretation: 'STATE_INTENSITY',
    },
    aggregationStrategy: {
      type: 'RECENCY_WEIGHTED',
      minimumEvidence: 1,
      expectedEvidence: 3,
      halfLifeDays: 7,
    },
    developmentPolicy: 'STATE_MANAGEMENT',
    pairStrategies: [
      {
        strategyVersion: 2,
        directionality: 'SYMMETRIC',
        context: 'COMMITTED_RELATIONSHIP',
        config: { type: 'TARGET_RANGE', targetMin: 0, targetMax: 0.75 },
        minimumConfidence: 0.35,
        actionability: 'AWARENESS',
      },
    ],
    privacyClass: 'PRIVATE',
    contexts: ['SELF', 'COMMITTED_RELATIONSHIP'],
    confidenceRequirements: weeklyStateConfidence,
    freshnessPolicy: weeklyStateFreshness,
    displayKeys: displayKeysFor('wellbeing.current.overload'),
    definitionVersion: 3,
  },
  {
    id: 'factor.wellbeingCurrentReadiness',
    key: 'wellbeing.current.readiness',
    domainKey: 'wellbeing',
    dimensionKey: 'wellbeing.current',
    title: 'Готовность к совместному действию',
    description: 'Текущая доступность внимания и энергии для небольшого совместного шага.',
    type: 'STATE',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    semantics: {
      kind: 'ORDERED',
      lowPole: { key: 'low_readiness', label: 'мало доступного ресурса' },
      highPole: { key: 'high_readiness', label: 'есть доступный ресурс' },
      labels: [],
      interpretation: 'AVAILABILITY',
    },
    aggregationStrategy: {
      type: 'RECENCY_WEIGHTED',
      minimumEvidence: 1,
      expectedEvidence: 3,
      halfLifeDays: 7,
    },
    developmentPolicy: 'STATE_MANAGEMENT',
    pairStrategies: [
      {
        strategyVersion: 2,
        directionality: 'SYMMETRIC',
        context: 'COMMITTED_RELATIONSHIP',
        config: { type: 'MINIMUM_BOTH', minimum: 0.35 },
        minimumConfidence: 0.35,
        actionability: 'AWARENESS',
      },
    ],
    privacyClass: 'PRIVATE',
    contexts: ['SELF', 'COMMITTED_RELATIONSHIP'],
    confidenceRequirements: weeklyStateConfidence,
    freshnessPolicy: weeklyStateFreshness,
    displayKeys: displayKeysFor('wellbeing.current.readiness'),
    definitionVersion: 2,
  },
  {
    id: 'factor.sharedLifePlanningStructurePreference',
    key: 'sharedLife.planning.structurePreference',
    domainKey: 'sharedLife',
    dimensionKey: 'sharedLife.planning',
    title: 'Предпочтение структуры',
    description: 'Положение между спонтанностью и заранее заданной структурой без оценки хорошо/плохо.',
    type: 'PREFERENCE_AXIS',
    valueSchema: { type: 'SCALAR', min: -1, max: 1 },
    semantics: {
      kind: 'BIPOLAR',
      lowPole: { key: 'spontaneity', label: 'больше спонтанности' },
      midpointLabel: 'гибкий баланс',
      highPole: { key: 'structure', label: 'больше структуры' },
      interpretation: 'NON_EVALUATIVE',
    },
    aggregationStrategy: { type: 'LATEST', minimumEvidence: 1 },
    developmentPolicy: 'NO_IMPROVEMENT',
    pairStrategies: [
      {
        strategyVersion: 2,
        directionality: 'SYMMETRIC',
        context: 'COHABITATION',
        config: { type: 'BOUNDED_GAP', comfortableGap: 0.4, maximumGap: 1.2 },
        minimumConfidence: 0.4,
        actionability: 'NEGOTIATION',
      },
    ],
    privacyClass: 'NORMAL',
    contexts: ['SELF', 'DATING', 'COMMITTED_RELATIONSHIP', 'COHABITATION'],
    confidenceRequirements: {
      minimumEvidenceReliability: 0.4,
      minimumSnapshotConfidence: 0.4,
      minimumPairConfidence: 0.4,
    },
    freshnessPolicy: { type: 'NON_EXPIRING' },
    displayKeys: displayKeysFor('sharedLife.planning.structurePreference'),
    definitionVersion: 2,
  },
  {
    id: 'factor.sharedLifeRolesHouseholdCapability',
    key: 'sharedLife.roles.householdCapability',
    domainKey: 'sharedLife',
    dimensionKey: 'sharedLife.roles',
    title: 'Покрытие бытовых ролей',
    description: 'Способность брать конкретные роли; оценивается вместе с нагрузкой и справедливостью.',
    type: 'ROLE_CAPABILITY',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    semantics: {
      kind: 'ORDERED',
      lowPole: { key: 'low_coverage', label: 'роль пока не покрывается' },
      highPole: { key: 'high_coverage', label: 'роль устойчиво покрывается' },
      labels: [],
      interpretation: 'CAPABILITY',
    },
    aggregationStrategy: {
      type: 'WEIGHTED_MEAN',
      minimumEvidence: 2,
      expectedEvidence: 4,
    },
    developmentPolicy: 'TRAINABLE',
    pairStrategies: [
      {
        strategyVersion: 2,
        directionality: 'SYMMETRIC',
        context: 'COHABITATION',
        config: {
          type: 'ROLE_COVERAGE',
          minimumCoverage: 0.6,
          maximumLoadImbalance: 0.35,
        },
        minimumConfidence: 0.4,
        actionability: 'ROLE_REDISTRIBUTION',
      },
    ],
    privacyClass: 'NORMAL',
    contexts: ['SELF', 'COMMITTED_RELATIONSHIP', 'COHABITATION'],
    confidenceRequirements: {
      minimumEvidenceReliability: 0.3,
      minimumSnapshotConfidence: 0.3,
      minimumPairConfidence: 0.4,
    },
    freshnessPolicy: {
      type: 'DECAY',
      halfLifeDays: 90,
      expiresAfterDays: 180,
    },
    displayKeys: displayKeysFor('sharedLife.roles.householdCapability'),
    definitionVersion: 2,
  },
  {
    id: 'factor.lifePlansFamilyChildrenIntent',
    key: 'lifePlans.family.childrenIntent',
    domainKey: 'lifePlans',
    dimensionKey: 'lifePlans.family',
    title: 'План о детях',
    description: 'Явное жизненное ограничение, которое не усредняется с косвенными сигналами.',
    type: 'CONSTRAINT',
    valueSchema: { type: 'CONSTRAINT', allowedValues: ['YES', 'NO', 'UNSURE'] },
    semantics: {
      kind: 'CATEGORICAL',
      labels: [
        { key: 'YES', label: 'хочу детей' },
        { key: 'NO', label: 'не хочу детей' },
        { key: 'UNSURE', label: 'пока не уверен(а)' },
      ],
      interpretation: 'NON_ORDINAL',
    },
    aggregationStrategy: { type: 'NON_AGGREGATING', minimumEvidence: 1 },
    developmentPolicy: 'FIXED_CONSTRAINT',
    pairStrategies: [
      {
        strategyVersion: 2,
        directionality: 'SYMMETRIC',
        context: 'DATING',
        config: {
          type: 'HARD_CONSTRAINT',
          allowedPairs: [
            { a: 'constraint:YES', b: 'constraint:YES' },
            { a: 'constraint:NO', b: 'constraint:NO' },
            { a: 'constraint:UNSURE', b: 'constraint:UNSURE' },
            { a: 'constraint:YES', b: 'constraint:UNSURE' },
            { a: 'constraint:UNSURE', b: 'constraint:YES' },
            { a: 'constraint:NO', b: 'constraint:UNSURE' },
            { a: 'constraint:UNSURE', b: 'constraint:NO' },
          ],
        },
        minimumConfidence: 0.8,
        actionability: 'DECISION_REQUIRED',
      },
    ],
    privacyClass: 'MATCHING_ONLY',
    contexts: ['SELF', 'DATING', 'MARRIAGE_PLANNING', 'PARENTING_PLANNING'],
    confidenceRequirements: {
      minimumEvidenceReliability: 0.8,
      minimumSnapshotConfidence: 0.8,
      minimumPairConfidence: 0.8,
    },
    freshnessPolicy: { type: 'NON_EXPIRING' },
    displayKeys: displayKeysFor('lifePlans.family.childrenIntent'),
    definitionVersion: 2,
  },
];

export const MVP_MEASUREMENTS_V6: readonly MeasurementDefinition[] = [
  {
    id: 'measurement.onboardingRepairSkill',
    key: 'onboarding.repairSkill.selfReport',
    factorKey: 'communication.conflict.repairSkill',
    sourceType: 'QUESTIONNAIRE',
    valueSchema: masterySchema,
    normalization: { type: 'IDENTITY' },
    reliability: 0.65,
    measurementVersion: 1,
  },
  {
    id: 'measurement.onboardingStructurePreference',
    key: 'onboarding.structurePreference.direct',
    factorKey: 'sharedLife.planning.structurePreference',
    sourceType: 'EXPLICIT_PROFILE',
    valueSchema: { type: 'SCALAR', min: -1, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.9,
    measurementVersion: 1,
  },
  {
    id: 'measurement.onboardingChildrenIntent',
    key: 'onboarding.childrenIntent.direct',
    factorKey: 'lifePlans.family.childrenIntent',
    sourceType: 'EXPLICIT_PROFILE',
    valueSchema: { type: 'CONSTRAINT', allowedValues: ['YES', 'NO', 'UNSURE'] },
    normalization: { type: 'IDENTITY' },
    reliability: 1,
    measurementVersion: 2,
  },
  {
    id: 'measurement.weeklyConnection',
    key: 'weekly.connection.direct',
    factorKey: 'communication.weekly.connection',
    sourceType: 'CHECK_IN',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.85,
    measurementVersion: 1,
  },
  {
    id: 'measurement.weeklyTension',
    key: 'weekly.tension.direct',
    factorKey: 'communication.weekly.tension',
    sourceType: 'CHECK_IN',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.85,
    measurementVersion: 1,
  },
  {
    id: 'measurement.weeklyOverload',
    key: 'weekly.overload.direct',
    factorKey: 'wellbeing.current.overload',
    sourceType: 'CHECK_IN',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.85,
    measurementVersion: 1,
  },
  {
    id: 'measurement.weeklyReadiness',
    key: 'weekly.readiness.direct',
    factorKey: 'wellbeing.current.readiness',
    sourceType: 'CHECK_IN',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.85,
    measurementVersion: 1,
  },
  {
    id: 'measurement.activityConnectionOutcome',
    key: 'activity.connection.outcome',
    factorKey: 'communication.weekly.connection',
    sourceType: 'TASK_RESULT',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.72,
    measurementVersion: 1,
  },
  {
    id: 'measurement.activityOverloadOutcome',
    key: 'activity.overload.outcome',
    factorKey: 'wellbeing.current.overload',
    sourceType: 'TASK_RESULT',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.7,
    measurementVersion: 1,
  },
  {
    id: 'measurement.activityRepairOutcome',
    key: 'activity.repairSkill.outcome',
    factorKey: 'communication.conflict.repairSkill',
    sourceType: 'TASK_RESULT',
    valueSchema: masterySchema,
    normalization: { type: 'IDENTITY' },
    reliability: 0.8,
    measurementVersion: 1,
  },
  {
    id: 'measurement.activityHouseholdCapability',
    key: 'activity.householdRole.capability',
    factorKey: 'sharedLife.roles.householdCapability',
    sourceType: 'TASK_RESULT',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.75,
    measurementVersion: 1,
  },
  {
    id: 'measurement.pairActivityConnectionOutcome',
    key: 'pairActivity.connection.outcome',
    factorKey: 'communication.weekly.connection',
    sourceType: 'PAIR_ACTIVITY',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.7,
    measurementVersion: 1,
  },
  {
    id: 'measurement.pairActivityOverloadOutcome',
    key: 'pairActivity.overload.outcome',
    factorKey: 'wellbeing.current.overload',
    sourceType: 'PAIR_ACTIVITY',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.68,
    measurementVersion: 1,
  },
  {
    id: 'measurement.pairActivityRepairOutcome',
    key: 'pairActivity.repairSkill.outcome',
    factorKey: 'communication.conflict.repairSkill',
    sourceType: 'PAIR_ACTIVITY',
    valueSchema: masterySchema,
    normalization: { type: 'IDENTITY' },
    reliability: 0.78,
    measurementVersion: 1,
  },
  {
    id: 'measurement.pairActivityHouseholdCapability',
    key: 'pairActivity.householdRole.capability',
    factorKey: 'sharedLife.roles.householdCapability',
    sourceType: 'PAIR_ACTIVITY',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.72,
    measurementVersion: 1,
  },
];

export const MVP_INSTRUMENTS_V6: readonly InstrumentDefinition[] = [
  {
    id: 'instrument.onboardingMvp',
    key: 'onboarding.mvp',
    title: 'Базовый профиль',
    context: 'SELF',
    measurementKeys: [
      'onboarding.repairSkill.selfReport',
      'onboarding.structurePreference.direct',
      'onboarding.childrenIntent.direct',
    ],
    instrumentVersion: 2,
  },
  {
    id: 'instrument.weeklyMvp',
    key: 'weekly.mvp',
    title: 'Недельный check-in',
    context: 'COMMITTED_RELATIONSHIP',
    measurementKeys: [
      'weekly.connection.direct',
      'weekly.tension.direct',
      'weekly.overload.direct',
      'weekly.readiness.direct',
    ],
    instrumentVersion: 2,
  },
  {
    id: 'instrument.activityReflectionMvp',
    key: 'activityReflection.mvp',
    title: 'Рефлексия после действия',
    context: 'COMMITTED_RELATIONSHIP',
    measurementKeys: [
      'activity.connection.outcome',
      'activity.overload.outcome',
      'activity.repairSkill.outcome',
      'activity.householdRole.capability',
      'pairActivity.connection.outcome',
      'pairActivity.overload.outcome',
      'pairActivity.repairSkill.outcome',
      'pairActivity.householdRole.capability',
    ],
    instrumentVersion: 2,
  },
];

export const MVP_ACTIONS: readonly ActionDefinition[] = [
  {
    id: 'action.gentleThreeMinuteCheckIn',
    key: 'action.gentleThreeMinuteCheckIn',
    title: 'Три минуты на контакт',
    description: 'Коротко назвать своё состояние без попытки решить всё сразу.',
    targetFactors: [
      'communication.weekly.connection',
      'wellbeing.current.overload',
    ],
    contexts: ['COMMITTED_RELATIONSHIP'],
    expectedOutcomes: ['outcome.contactNamed', 'outcome.loadAcknowledged'],
    contraindications: [
      {
        type: 'FACTOR_AT_OR_ABOVE',
        factorKey: 'communication.weekly.tension',
        threshold: 0.95,
      },
    ],
    difficulty: 1,
    durationMinutes: 10,
    cooldownDays: 7,
    feedbackSchemaKey: 'activity-feedback-v2',
    publicationVersion: 1,
    actionVersion: 1,
  },
  {
    id: 'action.repairConversation',
    key: 'action.repairConversation',
    title: 'Вернуться к сложному разговору',
    description: 'Провести короткий разговор по шагам восстановления контакта.',
    targetFactors: ['communication.conflict.repairSkill'],
    minimumSkillLevel: 'INTERMEDIATE',
    minimumSkillFactorKey: 'communication.conflict.repairSkill',
    contexts: ['COMMITTED_RELATIONSHIP'],
    expectedOutcomes: ['outcome.repairAttempted', 'outcome.requestNamed'],
    contraindications: [
      {
        type: 'FACTOR_AT_OR_ABOVE',
        factorKey: 'wellbeing.current.overload',
        threshold: 0.75,
      },
    ],
    difficulty: 3,
    durationMinutes: 20,
    cooldownDays: 14,
    feedbackSchemaKey: 'activity-feedback-v2',
    publicationVersion: 1,
    actionVersion: 1,
  },
  {
    id: 'action.householdRoleMap',
    key: 'action.householdRoleMap',
    title: 'Карта бытовых ролей',
    description: 'Выбрать несколько ролей и проверить покрытие, нагрузку и ощущение справедливости.',
    targetFactors: ['sharedLife.roles.householdCapability'],
    contexts: ['COMMITTED_RELATIONSHIP', 'COHABITATION'],
    expectedOutcomes: ['outcome.rolesNamed', 'outcome.loadDiscussed'],
    contraindications: [
      {
        type: 'FACTOR_AT_OR_ABOVE',
        factorKey: 'communication.weekly.tension',
        threshold: 0.85,
      },
    ],
    difficulty: 2,
    durationMinutes: 25,
    cooldownDays: 14,
    feedbackSchemaKey: 'activity-feedback-v2',
    publicationVersion: 1,
    actionVersion: 1,
  },
];

export const MVP_FACTOR_REGISTRY_V6_INPUT: UnhashedFactorRegistryRelease = {
  registryKey: 'foreverApp.factorEngine.mvp',
  registryVersion: 6,
  algorithmVersion: 4,
  snapshotVersion: 3,
  displayVersion: 3,
  status: 'PUBLISHED',
  domains: MVP_DOMAINS,
  dimensions: MVP_DIMENSIONS_V6,
  factors: MVP_FACTORS_V6,
  measurements: MVP_MEASUREMENTS_V6,
  instruments: MVP_INSTRUMENTS_V6,
  actions: MVP_ACTIONS,
};

export const MVP_FACTOR_REGISTRY_V6 = createFactorRegistryRelease(
  MVP_FACTOR_REGISTRY_V6_INPUT
);

const MATCHING_POLICY_INTERNAL = {
  engineUse: 'INTERNAL_ONLY',
  explanation: 'COARSE_ALLOWLISTED',
} as const;

const relationshipIntentFactor: FactorDefinition = {
  id: 'factor.lifePlansRelationshipIntent',
  key: 'lifePlans.relationship.intent',
  domainKey: 'lifePlans',
  dimensionKey: 'lifePlans.relationship',
  title: 'Намерение строить отношения',
  description: 'Текущее явно выбранное намерение знакомиться и развивать отношения.',
  type: 'EXPECTATION',
  valueSchema: {
    type: 'ORDINAL',
    levels: [
      { value: 'GETTING_TO_KNOW', rank: 0, label: 'знакомиться без спешки' },
      { value: 'OPEN_TO_RELATIONSHIP', rank: 1, label: 'открыт(а) отношениям' },
      { value: 'LOOKING_FOR_LONG_TERM', rank: 2, label: 'ищу долгосрочные отношения' },
    ],
  },
  semantics: {
    kind: 'ORDERED',
    lowPole: { key: 'exploration', label: 'знакомство без спешки' },
    highPole: { key: 'long_term', label: 'долгосрочное намерение' },
    labels: [
      { key: 'GETTING_TO_KNOW', label: 'знакомиться без спешки' },
      { key: 'OPEN_TO_RELATIONSHIP', label: 'открыт(а) отношениям' },
      { key: 'LOOKING_FOR_LONG_TERM', label: 'ищу долгосрочные отношения' },
    ],
    interpretation: 'AVAILABILITY',
  },
  aggregationStrategy: { type: 'LATEST', minimumEvidence: 1 },
  developmentPolicy: 'REFLECTION_ONLY',
  pairStrategies: [
    {
      strategyVersion: 2,
      directionality: 'SYMMETRIC',
      context: 'DATING',
      config: { type: 'SIMILARITY', maximumDistance: 2 },
      minimumConfidence: 0.7,
      actionability: 'AWARENESS',
    },
  ],
  matchingPolicy: {
    enabled: true,
    effects: ['ELIGIBILITY', 'RANKING'],
    strategy: { context: 'DATING', type: 'SIMILARITY', strategyVersion: 2 },
    requiredData: 'BOTH_REQUIRED',
    defaultImportance: 'HIGH',
    rankingWeight: 0.9,
    canBeHardConstraint: false,
    privacy: MATCHING_POLICY_INTERNAL,
  },
  privacyClass: 'MATCHING_ONLY',
  contexts: ['SELF', 'DATING'],
  confidenceRequirements: {
    minimumEvidenceReliability: 0.7,
    minimumSnapshotConfidence: 0.7,
    minimumPairConfidence: 0.7,
  },
  freshnessPolicy: { type: 'NON_EXPIRING' },
  displayKeys: displayKeysFor('lifePlans.relationship.intent'),
  definitionVersion: 1,
};

const socialActivityPreferenceFactor: FactorDefinition = {
  id: 'factor.sharedLifeLifestyleSocialActivityPreference',
  key: 'sharedLife.lifestyle.socialActivityPreference',
  domainKey: 'sharedLife',
  dimensionKey: 'sharedLife.lifestyle',
  title: 'Ритм социальной активности',
  description: 'Комфортный баланс между спокойным и насыщенным социальным ритмом.',
  type: 'PREFERENCE_AXIS',
  valueSchema: { type: 'SCALAR', min: -1, max: 1 },
  semantics: {
    kind: 'BIPOLAR',
    lowPole: { key: 'quiet_rhythm', label: 'более спокойный ритм' },
    midpointLabel: 'гибкий социальный ритм',
    highPole: { key: 'active_rhythm', label: 'более активный ритм' },
    interpretation: 'NON_EVALUATIVE',
  },
  aggregationStrategy: { type: 'LATEST', minimumEvidence: 1 },
  developmentPolicy: 'NO_IMPROVEMENT',
  pairStrategies: [
    {
      strategyVersion: 2,
      directionality: 'SYMMETRIC',
      context: 'DATING',
      config: { type: 'BOUNDED_GAP', comfortableGap: 0.5, maximumGap: 1.5 },
      minimumConfidence: 0.45,
      actionability: 'NEGOTIATION',
    },
  ],
  matchingPolicy: {
    enabled: true,
    effects: ['RANKING', 'EXPLANATION', 'POST_MATCH'],
    strategy: { context: 'DATING', type: 'BOUNDED_GAP', strategyVersion: 2 },
    requiredData: 'OPTIONAL',
    defaultImportance: 'MEDIUM',
    rankingWeight: 0.6,
    canBeHardConstraint: false,
    privacy: MATCHING_POLICY_INTERNAL,
  },
  privacyClass: 'NORMAL',
  contexts: ['SELF', 'DATING'],
  confidenceRequirements: {
    minimumEvidenceReliability: 0.45,
    minimumSnapshotConfidence: 0.45,
    minimumPairConfidence: 0.45,
  },
  freshnessPolicy: { type: 'NON_EXPIRING' },
  displayKeys: displayKeysFor('sharedLife.lifestyle.socialActivityPreference'),
  definitionVersion: 1,
};

const cleaningRolePreferenceFactor: FactorDefinition = {
  id: 'factor.sharedLifeRolesCleaningPreference',
  key: 'sharedLife.roles.cleaningPreference',
  domainKey: 'sharedLife',
  dimensionKey: 'sharedLife.roles',
  title: 'Предпочтение роли в уборке',
  description: 'Личная готовность регулярно брать на себя задачи уборки без оценки человека.',
  type: 'ROLE_PREFERENCE',
  valueSchema: { type: 'SCALAR', min: 0, max: 1 },
  semantics: {
    kind: 'ORDERED',
    lowPole: { key: 'avoid_cleaning', label: 'предпочитаю не брать эту роль' },
    highPole: { key: 'ready_for_cleaning', label: 'готов(а) брать эту роль' },
    labels: [],
    interpretation: 'AVAILABILITY',
  },
  aggregationStrategy: { type: 'LATEST', minimumEvidence: 1 },
  developmentPolicy: 'NEGOTIABLE',
  pairStrategies: [
    {
      strategyVersion: 2,
      directionality: 'SYMMETRIC',
      context: 'DATING',
      config: {
        type: 'BOUNDED_COMPLEMENT',
        minimumUsefulGap: 0.25,
        idealGap: 0.75,
        maximumGap: 1,
      },
      minimumConfidence: 0.45,
      actionability: 'ROLE_REDISTRIBUTION',
    },
  ],
  matchingPolicy: {
    enabled: true,
    effects: ['RANKING', 'EXPLANATION', 'POST_MATCH'],
    strategy: {
      context: 'DATING',
      type: 'BOUNDED_COMPLEMENT',
      strategyVersion: 2,
    },
    requiredData: 'OPTIONAL',
    defaultImportance: 'MEDIUM',
    rankingWeight: 0.55,
    canBeHardConstraint: false,
    privacy: MATCHING_POLICY_INTERNAL,
  },
  privacyClass: 'NORMAL',
  contexts: ['SELF', 'DATING', 'COHABITATION'],
  confidenceRequirements: {
    minimumEvidenceReliability: 0.45,
    minimumSnapshotConfidence: 0.45,
    minimumPairConfidence: 0.45,
  },
  freshnessPolicy: { type: 'NON_EXPIRING' },
  displayKeys: displayKeysFor('sharedLife.roles.cleaningPreference'),
  definitionVersion: 1,
};

const relationshipPriorityFactor: FactorDefinition = {
  id: 'factor.sharedLifeValuesRelationshipPriority',
  key: 'sharedLife.values.relationshipPriority',
  domainKey: 'sharedLife',
  dimensionKey: 'sharedLife.values',
  title: 'Место отношений среди приоритетов',
  description: 'Текущая готовность выделять отношениям время и внимание наряду с другими сферами жизни.',
  type: 'VALUE',
  valueSchema: { type: 'SCALAR', min: 0, max: 1 },
  semantics: {
    kind: 'ORDERED',
    lowPole: { key: 'limited_priority', label: 'сейчас мало места' },
    highPole: { key: 'high_priority', label: 'готов(а) выделять место' },
    labels: [],
    interpretation: 'AVAILABILITY',
  },
  aggregationStrategy: { type: 'LATEST', minimumEvidence: 1 },
  developmentPolicy: 'REFLECTION_ONLY',
  pairStrategies: [
    {
      strategyVersion: 2,
      directionality: 'SYMMETRIC',
      context: 'DATING',
      config: { type: 'SIMILARITY', maximumDistance: 0.8 },
      minimumConfidence: 0.5,
      actionability: 'AWARENESS',
    },
  ],
  matchingPolicy: {
    enabled: true,
    effects: ['RANKING', 'EXPLANATION'],
    strategy: { context: 'DATING', type: 'SIMILARITY', strategyVersion: 2 },
    requiredData: 'OPTIONAL',
    defaultImportance: 'HIGH',
    rankingWeight: 0.7,
    canBeHardConstraint: false,
    privacy: MATCHING_POLICY_INTERNAL,
  },
  privacyClass: 'NORMAL',
  contexts: ['SELF', 'DATING'],
  confidenceRequirements: {
    minimumEvidenceReliability: 0.5,
    minimumSnapshotConfidence: 0.5,
    minimumPairConfidence: 0.5,
  },
  freshnessPolicy: { type: 'NON_EXPIRING' },
  displayKeys: displayKeysFor('sharedLife.values.relationshipPriority'),
  definitionVersion: 1,
};

export const MVP_DIMENSIONS: readonly DimensionDefinition[] = [
  ...MVP_DIMENSIONS_V6,
  {
    id: 'dimension.sharedLifeLifestyle',
    key: 'sharedLife.lifestyle',
    domainKey: 'sharedLife',
    title: 'Ритм жизни',
    description: 'Предпочитаемый ритм повседневной и социальной жизни.',
    order: 30,
    version: 1,
  },
  {
    id: 'dimension.sharedLifeValues',
    key: 'sharedLife.values',
    domainKey: 'sharedLife',
    title: 'Приоритеты отношений',
    description: 'Явные, недиагностические приоритеты времени и внимания.',
    order: 40,
    version: 1,
  },
  {
    id: 'dimension.lifePlansRelationship',
    key: 'lifePlans.relationship',
    domainKey: 'lifePlans',
    title: 'Намерение отношений',
    description: 'Текущее явно выбранное намерение знакомства и отношений.',
    order: 20,
    version: 1,
  },
];

export const MVP_FACTORS: readonly FactorDefinition[] = [
  ...MVP_FACTORS_V6.map((factor): FactorDefinition => {
    if (factor.key === 'communication.conflict.repairSkill') {
      return {
        ...factor,
        pairStrategies: [
          ...factor.pairStrategies,
          {
            strategyVersion: 2,
            directionality: 'SYMMETRIC',
            context: 'DATING',
            config: { type: 'MINIMUM_BOTH', minimum: 0.4 },
            minimumConfidence: 0.35,
            actionability: 'SKILL_BUILDING',
          },
        ],
        matchingPolicy: {
          enabled: true,
          effects: ['RANKING', 'EXPLANATION', 'POST_MATCH'],
          strategy: { context: 'DATING', type: 'MINIMUM_BOTH', strategyVersion: 2 },
          requiredData: 'OPTIONAL',
          defaultImportance: 'MEDIUM',
          rankingWeight: 0.65,
          canBeHardConstraint: false,
          privacy: MATCHING_POLICY_INTERNAL,
        },
        definitionVersion: 3,
      };
    }
    if (factor.key === 'sharedLife.planning.structurePreference') {
      return {
        ...factor,
        pairStrategies: [
          ...factor.pairStrategies,
          {
            strategyVersion: 2,
            directionality: 'SYMMETRIC',
            context: 'DATING',
            config: { type: 'BOUNDED_GAP', comfortableGap: 0.4, maximumGap: 1.2 },
            minimumConfidence: 0.4,
            actionability: 'NEGOTIATION',
          },
        ],
        matchingPolicy: {
          enabled: true,
          effects: ['RANKING', 'EXPLANATION', 'POST_MATCH'],
          strategy: { context: 'DATING', type: 'BOUNDED_GAP', strategyVersion: 2 },
          requiredData: 'OPTIONAL',
          defaultImportance: 'HIGH',
          rankingWeight: 0.75,
          canBeHardConstraint: false,
          privacy: MATCHING_POLICY_INTERNAL,
        },
        definitionVersion: 3,
      };
    }
    if (factor.key === 'lifePlans.family.childrenIntent') {
      return {
        ...factor,
        matchingPolicy: {
          enabled: true,
          effects: ['ELIGIBILITY', 'RANKING'],
          strategy: { context: 'DATING', type: 'HARD_CONSTRAINT', strategyVersion: 2 },
          requiredData: 'BOTH_REQUIRED',
          defaultImportance: 'CRITICAL',
          rankingWeight: 1,
          canBeHardConstraint: true,
          privacy: { engineUse: 'INTERNAL_ONLY', explanation: 'NONE' },
        },
        definitionVersion: 3,
      };
    }
    return factor;
  }),
  relationshipIntentFactor,
  socialActivityPreferenceFactor,
  cleaningRolePreferenceFactor,
  relationshipPriorityFactor,
];

const MATCHING_MEASUREMENTS: readonly MeasurementDefinition[] = [
  {
    id: 'measurement.matchingRepairSkill',
    key: 'matching.repairSkill.selfReport',
    factorKey: 'communication.conflict.repairSkill',
    sourceType: 'EXPLICIT_PROFILE',
    valueSchema: masterySchema,
    normalization: { type: 'IDENTITY' },
    reliability: 0.72,
    measurementVersion: 1,
  },
  {
    id: 'measurement.matchingStructurePreference',
    key: 'matching.structurePreference.direct',
    factorKey: 'sharedLife.planning.structurePreference',
    sourceType: 'EXPLICIT_PROFILE',
    valueSchema: { type: 'SCALAR', min: -1, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.9,
    measurementVersion: 1,
  },
  {
    id: 'measurement.matchingChildrenIntent',
    key: 'matching.childrenIntent.direct',
    factorKey: 'lifePlans.family.childrenIntent',
    sourceType: 'EXPLICIT_PROFILE',
    valueSchema: { type: 'CONSTRAINT', allowedValues: ['YES', 'NO', 'UNSURE'] },
    normalization: { type: 'IDENTITY' },
    reliability: 1,
    measurementVersion: 1,
  },
  {
    id: 'measurement.matchingRelationshipIntent',
    key: 'matching.relationshipIntent.direct',
    factorKey: 'lifePlans.relationship.intent',
    sourceType: 'EXPLICIT_PROFILE',
    valueSchema: relationshipIntentFactor.valueSchema,
    normalization: { type: 'IDENTITY' },
    reliability: 0.95,
    measurementVersion: 1,
  },
  {
    id: 'measurement.matchingSocialActivityPreference',
    key: 'matching.socialActivityPreference.direct',
    factorKey: 'sharedLife.lifestyle.socialActivityPreference',
    sourceType: 'EXPLICIT_PROFILE',
    valueSchema: { type: 'SCALAR', min: -1, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.9,
    measurementVersion: 1,
  },
  {
    id: 'measurement.matchingCleaningPreference',
    key: 'matching.cleaningPreference.direct',
    factorKey: 'sharedLife.roles.cleaningPreference',
    sourceType: 'EXPLICIT_PROFILE',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.9,
    measurementVersion: 1,
  },
  {
    id: 'measurement.matchingRelationshipPriority',
    key: 'matching.relationshipPriority.direct',
    factorKey: 'sharedLife.values.relationshipPriority',
    sourceType: 'EXPLICIT_PROFILE',
    valueSchema: { type: 'SCALAR', min: 0, max: 1 },
    normalization: { type: 'IDENTITY' },
    reliability: 0.9,
    measurementVersion: 1,
  },
];

export const MVP_MEASUREMENTS: readonly MeasurementDefinition[] = [
  ...MVP_MEASUREMENTS_V6,
  ...MATCHING_MEASUREMENTS,
];

export const MVP_INSTRUMENTS: readonly InstrumentDefinition[] = [
  ...MVP_INSTRUMENTS_V6,
  {
    id: 'instrument.matchingProfileMvp',
    key: 'matching.profile.mvp',
    title: 'Профиль для знакомств',
    context: 'DATING',
    measurementKeys: MATCHING_MEASUREMENTS.map((measurement) => measurement.key),
    instrumentVersion: 1,
  },
];

export const MVP_FACTOR_REGISTRY_INPUT: UnhashedFactorRegistryRelease = {
  registryKey: 'foreverApp.factorEngine.mvp',
  registryVersion: 7,
  algorithmVersion: 5,
  snapshotVersion: 3,
  displayVersion: 4,
  status: 'PUBLISHED',
  domains: MVP_DOMAINS,
  dimensions: MVP_DIMENSIONS,
  factors: MVP_FACTORS,
  measurements: MVP_MEASUREMENTS,
  instruments: MVP_INSTRUMENTS,
  actions: MVP_ACTIONS,
};

export const MVP_FACTOR_REGISTRY = createFactorRegistryRelease(
  MVP_FACTOR_REGISTRY_INPUT
);
