export type MeasurementQuestion = { id: string; text: string; required: boolean; measurementKey: string; choices: readonly [string, string, string] };
export type MeasurementTest = { key: string; revision: number; area: string; title: string; purpose: string; matching: boolean; questions: readonly MeasurementQuestion[] };
const PUBLICATIONS_V1: readonly MeasurementTest[] = [
  { key: 'conversation', revision: 1, area: 'Общение', title: 'Как я восстанавливаю разговор', purpose: 'Разобраться, какие шаги восстановления уже удаются в разных ситуациях.', matching: true, questions: [
    { id: 'pause', text: 'Вспомните последний разговор, где вы взяли паузу из-за своего раздражения. Как удалось вернуться?', required: false, measurementKey: 'profile.conversation.pause', choices: ['Без подсказки вернуться не удалось', 'Вернулись, но договориться удалось частично', 'Самостоятельно вернулись и согласовали следующий шаг'] },
    { id: 'misunderstanding', text: 'Теперь вспомните ДРУГОЙ разговор, где собеседник неверно понял вас. Как удалось восстановить понимание? Если второго эпизода нет — пропустите.', required: false, measurementKey: 'profile.conversation.misunderstanding', choices: ['Потребовалась помощь со стороны', 'Удалось уточнить часть смысла', 'Уточнили смысл и проверили, что поняли друг друга'] },
  ] },
  { key: 'planning', revision: 1, area: 'Быт и забота', title: 'Мой ритм планирования', purpose: 'Понять комфортный баланс спонтанности и договорённостей о времени.', matching: true, questions: [{ id: 'time', text: 'Как вам комфортнее выбирать время для совместных дел?', required: true, measurementKey: 'profile.planning.time', choices: ['Решать в тот же день', 'Выбирать гибкое окно', 'Заранее фиксировать время'] }] },
  { key: 'priorities', revision: 1, area: 'Взгляды и ценности', title: 'Место отношений в моей жизни', purpose: 'Назвать доступное место для отношений среди других важных занятий.', matching: true, questions: [{ id: 'time', text: 'Сколько места вы сейчас готовы выделять отношениям в расписании?', required: true, measurementKey: 'profile.priorities.time', choices: ['Пока немного', 'Наряду с другими важными сферами', 'Значимое место и регулярное время'] }] },
  { key: 'money', revision: 1, area: 'Финансовые договорённости', title: 'Как обсуждать расходы', purpose: 'Определить предпочтение обсуждать траты, затрагивающие общие планы. Доход не измеряется.', matching: false, questions: [{ id: 'discussion', text: 'Какой порядок расходов в рамках общих планов вам комфортнее?', required: true, measurementKey: 'profile.money.discussion', choices: ['Самостоятельность в согласованных пределах', 'Обсуждать крупные или необычные траты', 'Предварительно согласовывать такие расходы'] }] },
  { key: 'boundaries', revision: 1, area: 'Интимность и границы', title: 'Разговор о близости', purpose: 'Назвать комфортный момент для обсуждения границ. Согласие добровольно и может быть отозвано в любой момент.', matching: false, questions: [{ id: 'discussion', text: 'Когда вам комфортнее обсуждать желания и границы близости?', required: false, measurementKey: 'profile.boundaries.discussion', choices: ['В моменте, проверяя согласие', 'Зависит от ситуации', 'Заранее, в отдельном разговоре'] }] },
  { key: 'recovery', revision: 1, area: 'Состояние и восстановление', title: 'Моя нагрузка сейчас', purpose: 'Заметить нагрузку за последние семь дней. Это временное состояние, а не черта личности.', matching: false, questions: [{ id: 'load', text: 'Как ощущалась нагрузка за последние семь дней?', required: true, measurementKey: 'profile.recovery.load', choices: ['Низкая: оставались силы на отдых', 'Заметная: отдых требовал внимания', 'Высокая: восстановиться было трудно'] }] },
];

// Keep old wording alongside the new publication; completion identity excludes revision.
const planningV1 = PUBLICATIONS_V1.find((test) => test.key === 'planning')!;
export const MEASUREMENT_PUBLICATIONS: readonly MeasurementTest[] = [...PUBLICATIONS_V1, { ...planningV1, revision: 2, questions: planningV1.questions.map((question) => ({ ...question, text: 'Если дело требует участия обоих, как вам комфортнее договориться о времени?' })) }];
export const MEASUREMENT_TESTS: readonly MeasurementTest[] = [...new Map(MEASUREMENT_PUBLICATIONS.map((test) => [test.key, test])).values()];
export const measurementPublication = (key: string, revision?: number): MeasurementTest | undefined =>
  (revision === undefined ? MEASUREMENT_TESTS : MEASUREMENT_PUBLICATIONS).find((test) => test.key === key && (revision === undefined || test.revision === revision));
