// Reference tests retained in full; imports target the application engine.
import test from 'node:test';
import assert from 'node:assert/strict';
import {parseProblem,evaluateModel,findConditionalPlans,skillAtLeast,intersectSets,intersectIntervals,isCertificateCurrent,paretoPlans} from '../../src/domain/assessment/engine/matching.ts';
import {laneFor,definitelyDominates,observedConditionSummary} from '../../src/domain/assessment/engine/discovery.ts';
import {agreementStatus,comparePairReports,ordinalReportTrend} from '../../src/domain/assessment/engine/pair.ts';
import {resolveLevels,classifyAgreement} from '../../src/domain/assessment/engine/core.ts';
import {problem,withTwoBarriers,worldDependent,f,not} from './fixtures.mjs';
const run=p=>{const x=evaluateModel(p);assert.equal(x.kind,'RESULT');return x.value;};
const search=p=>{const x=findConditionalPlans(p);assert.equal(x.kind,'SEARCH');return x;};
const clone=p=>JSON.parse(JSON.stringify(p));
function change(p,id,effects,owners=['B']){return {...clone(p.changes[0]),id,effects,owners,costs:{},prerequisites:[],willingness:{A:'T',B:'T'}};}

test('strict problem schema rejects unexpected outer key',()=>assert.throws(()=>parseProblem({...problem(),secret:1}),/UNEXPECTED_FIELD/));
test('duplicate fact rejected',()=>{const p=problem();p.factDefinitions.push(p.factDefinitions[0]);assert.throws(()=>parseProblem(p),/DUPLICATE_FACT/);});
test('unknown expression reference rejected',()=>{const p=problem();p.requirements[0].predicate=f('invented');assert.throws(()=>parseProblem(p),/INVALID_RULE_REFERENCE/);});
test('empty all expression rejected',()=>{const p=problem();p.requirements[0].predicate={op:'ALL',args:[]};assert.throws(()=>parseProblem(p),/INVALID_RULE_ARGS/);});
test('duplicate requirement rejected',()=>{const p=problem();p.requirements.push(p.requirements[0]);assert.throws(()=>parseProblem(p),/DUPLICATE_REQUIREMENT/);});
test('unknown resource rejected',()=>{const p=problem();p.configurations[0].use.fake=3;assert.throws(()=>parseProblem(p),/UNKNOWN_RESOURCE/);});
test('negative resource rejected',()=>{const p=problem();p.resources[0].capacity=-1;assert.throws(()=>parseProblem(p),/INVALID_INTEGER/);});
test('cyclic prerequisite rejected',()=>{const p=problem();p.changes[0].prerequisites=[p.changes[0].id];assert.throws(()=>parseProblem(p),/CYCLIC_CHANGES/);});
test('empty effect rejected',()=>{const p=problem();p.changes[0].effects={};assert.throws(()=>parseProblem(p),/EMPTY_EFFECTS/);});
test('cannot mutate fixed goals as recourse',()=>{const p=problem();p.changes[0].effects={sameParenthood:'T'};assert.throws(()=>parseProblem(p),/PROTECTED_FACT_CHANGE/);});
test('cannot relax a personal boundary',()=>{const p=problem();p.changes[0].effects={Bautonomy:'T'};assert.throws(()=>parseProblem(p),/PROTECTED_FACT_CHANGE/);});
test('cannot erase event history',()=>{const p=problem();p.factDefinitions.push({id:'past',kind:'HISTORY',owner:'B',domain:'D02'});p.snapshot.values.past='T';p.changes[0].effects={past:'F'};assert.throws(()=>parseProblem(p),/PROTECTED_FACT_CHANGE/);});
test('cannot remove a safety signal',()=>{const p=problem();p.factDefinitions.push({id:'safety',kind:'SAFETY',owner:'B',domain:'D02'});p.snapshot.values.safety='T';p.changes[0].effects={safety:'F'};assert.throws(()=>parseProblem(p),/PROTECTED_FACT_CHANGE/);});
test('cannot erase evidence to unknown as an action',()=>{const p=problem();p.changes[0].effects={BfullCycle:'U'};assert.throws(()=>parseProblem(p),/CANNOT_ERASE/);});
test('cannot lower requested skill as an improvement',()=>{const p=problem();p.changes[0].effects={BfullCycle:'F'};assert.throws(()=>parseProblem(p),/SKILL_ACTION/);});
test('one person cannot commit another to change',()=>{const p=problem();p.changes[0].owners=['A'];assert.throws(()=>parseProblem(p),/UNAUTHORISED_ACTION_OWNER/);});
test('cost cannot be silently shifted to the other person',()=>{const p=problem();p.changes[0].costs={A_minutes:90};assert.throws(()=>parseProblem(p),/UNCONSENTED_BURDEN_TRANSFER/);});
test('all plan decision variables must be explicit',()=>{const p=worldDependent();p.configurations[0].choices={};assert.throws(()=>parseProblem(p),/INCOMPLETE_PLAN_CHOICES/);});
test('plan choice cannot arrive as actual profile fact',()=>{const p=worldDependent();p.snapshot.values.chooseEarly='T';assert.throws(()=>parseProblem(p),/INVALID_SNAPSHOT_FACT/);});

test('known current mismatch is not averaged away',()=>{const x=run(problem());assert.equal(x.status,'NO_TARGET_PLAN_IN_CATALOG');assert.ok(x.independentFailingRequirements.includes('A_need_shopping_cycle'));});
test('one domain achieved-state assumption yields a conditional witness',()=>{const x=search(problem());assert.equal(x.plans.length,1);assert.deepEqual(x.plans[0].changedDomains,['D01']);assert.equal(x.plans[0].after.samePlanWorksAcrossWorlds,true);assert.equal(laneFor(x),'CONDITIONAL_OPTION');});
test('simulation leaves current snapshot byte-for-byte unchanged',()=>{const p=problem(),before=JSON.stringify(p);findConditionalPlans(p);assert.equal(JSON.stringify(p),before);assert.equal(run(p).status,'NO_TARGET_PLAN_IN_CATALOG');});
test('completion promise never automatically changes current match',()=>{const p=problem();p.changes[0].willingness.B='T';assert.equal(run(p).status,'NO_TARGET_PLAN_IN_CATALOG');});
test('already meeting target does not manufacture development needs',()=>{const p=problem();p.snapshot.values.BfullCycle='T';const x=search(p);assert.equal(x.plans.length,0);assert.equal(laneFor(x),'CURRENT_SUPPORTED');});
test('explicit refusal removes that route, not the preference',()=>{const p=problem();p.changes[0].willingness.B='F';const x=search(p);assert.equal(x.plans.length,0);assert.ok(x.rejected.some(r=>r.reason==='CHANGE_EXPLICITLY_DECLINED'));});
test('unknown willingness permits only an unchosen mathematical option',()=>{const p=problem();p.changes[0].willingness.B='U';const x=search(p);assert.equal(x.plans[0].phase,'MODEL_OPTION_NOT_CHOSEN');});
test('declared openness is not a joint agreement',()=>assert.equal(search(problem()).plans[0].phase,'DECLARED_OPEN_NOT_AGREED'));
test('unknown skill prioritises clarification rather than asserting a deficit',()=>{const p=problem();p.snapshot.values.BfullCycle='U';const x=search(p);assert.equal(x.current.status,'NEEDS_CLARIFICATION');assert.equal(laneFor(x),'CLARIFY_FIRST');});
test('skill cannot substitute for a missing offer',()=>{const p=problem();p.snapshot.values.BoffersShopping='F';assert.equal(search(p).plans.length,0);});
test('unknown offer cannot be treated as an offered service',()=>{const p=problem();p.snapshot.values.BoffersShopping='U';assert.equal(search(p).plans.length,0);});
test('fundamental parenting mismatch is not solved by household skill',()=>{const p=problem();p.snapshot.values.sameParenthood='F';assert.equal(search(p).plans.length,0);});
test('global time budget includes both task and intervention burden',()=>{const p=problem();p.resources[1].capacity=240;assert.equal(search(p).plans.length,0);});
test('exact resource boundary is feasible in integer units',()=>{const p=problem();p.resources[1].capacity=270;assert.equal(search(p).plans.length,1);});
test('unknown resource cannot yield robust feasibility',()=>{const p=problem();p.resources[1].capacity=null;const x=search(p);assert.equal(x.plans.length,0);const y=evaluateModel(p,[p.changes[0].id]);assert.equal(y.value.status,'NEEDS_CLARIFICATION');});
test('blocked contact overrides all positive facts and scenarios',()=>{const p=problem();p.snapshot.gate='UNAVAILABLE';p.snapshot.values.BfullCycle='T';assert.deepEqual(evaluateModel(p),{kind:'UNAVAILABLE'});assert.deepEqual(findConditionalPlans(p),{kind:'UNAVAILABLE'});});
test('unavailable output does not expose private reason or profiles',()=>{const p=problem();p.snapshot.gate='UNAVAILABLE';const a=evaluateModel(p);p.snapshot.values.sameParenthood='F';assert.deepEqual(a,evaluateModel(p));});
test('two barriers require a joint action set even when neither single action succeeds',()=>{const p=withTwoBarriers(),x=search(p);assert.equal(x.plans.length,1);assert.equal(x.plans[0].actionIds.length,2);assert.deepEqual(x.plans[0].changedDomains,['D01','D09']);assert.deepEqual(x.singleDomainRouteIds,[]);});
test('action cap limits the stated search universe; no global impossibility claim',()=>{const x=findConditionalPlans(withTwoBarriers(),{maxActionsPerSet:1});assert.equal(x.plans.length,0);assert.equal(x.completeness,'COMPLETE_WITHIN_LIMITS');});
test('multi-action costs are joint, not evaluated separately',()=>{const p=withTwoBarriers();p.resources[1].capacity=280;assert.equal(search(p).plans.length,0);});
test('prerequisites must belong to the same set',()=>{const p=withTwoBarriers();p.changes[0].prerequisites=['joint_schedule'];const x=search(p);assert.equal(x.plans[0].actionIds.length,2);assert.ok(x.rejected.some(r=>r.reason==='MISSING_PREREQUISITE'));});
test('conflicting changes are rejected, not last-write-wins',()=>{const p=withTwoBarriers();p.changes.push(change(p,'cancel_schedule',{timeFits:'F'},['A','B']));assert.throws(()=>evaluateModel(p,['joint_schedule','cancel_schedule']),/CONFLICTING_EFFECTS/);});
test('precondition cannot be created by the action itself',()=>{const p=problem();p.changes[0].precondition=f('BfullCycle');assert.equal(search(p).plans.length,0);});
test('cannot ignore structural invariants after a hypothetical change',()=>{const p=problem();p.worldConstraints=[not('BfullCycle')];assert.equal(search(p).plans.length,0);});
test('contradictory current facts and world invariants produce input error',()=>{const p=problem();p.worldConstraints=[f('BfullCycle')];assert.throws(()=>run(p),/INCONSISTENT_INPUT_MODEL/);});

test('different feasible plan per world is NOT one agreed robust plan',()=>{const x=run(worldDependent());assert.equal(x.targetPossibleInEveryWorld,true);assert.equal(x.samePlanWorksAcrossWorlds,false);assert.equal(x.status,'NEEDS_CLARIFICATION');});
test('one disjunctive condition respects correlated repeated unknown symbol',()=>{const p=worldDependent();p.requirements[0].predicate={op:'ANY',args:[f('unknownDay'),not('unknownDay')]};const x=run(p);assert.equal(x.status,'TARGET_SUPPORTED');});
test('mutually exclusive individually possible conditions do not create a feasible conjunction',()=>{const p=worldDependent();p.requirements=[{id:'needYes',domain:'D09',direction:'A_FROM_B',tier:'MUST',predicate:f('unknownDay')},{id:'needNo',domain:'D09',direction:'B_FROM_A',tier:'MUST',predicate:not('unknownDay')}];assert.equal(run(p).status,'NO_TARGET_PLAN_IN_CATALOG');});
test('budget exhaustion is not no-solution',()=>{assert.equal(evaluateModel(worldDependent(),[],{maxChecks:1}).kind,'BUDGET_EXCEEDED');assert.equal(findConditionalPlans(problem(),{maxChecks:1}).completeness,'BUDGET_EXCEEDED');});
test('world cap never picks the optimistic completion',()=>assert.equal(evaluateModel(worldDependent(),[],{maxWorlds:1}).kind,'BUDGET_EXCEEDED'));
test('action-set budget is reported explicitly',()=>{const x=findConditionalPlans(withTwoBarriers(),{maxActionSets:1});assert.equal(x.completeness,'BUDGET_EXCEEDED');assert.equal(laneFor(x),'CLARIFY_FIRST');});
test('duplicate selected scenario id rejected',()=>{const p=problem(),a=p.changes[0].id;assert.throws(()=>evaluateModel(p,[a,a]),/DUPLICATE_SELECTED_CHANGE/);});
test('inclusion-minimal solution sets do not include irrelevant extra action',()=>{const p=problem();p.changes.push(change(p,'already_offers',{BoffersShopping:'T'}));const x=search(p);assert.ok(x.plans.every(y=>y.actionIds.length===1));});
test('permutation of inputs preserves conditional solutions',()=>{const p=withTwoBarriers();const x=search(p).plans.map(v=>v.actionIds);p.requirements.reverse();p.changes.reverse();p.factDefinitions.reverse();assert.deepEqual(search(p).plans.map(v=>v.actionIds),x);});
test('side-effect burden can affect another domain without adding fake independent benefit',()=>{const p=problem();p.requirements.push({id:'crossDomainSkill',domain:'D02',direction:'BOTH',tier:'PREFERENCE',predicate:f('BfullCycle')});const x=search(p).plans[0];assert.deepEqual(x.changedDomains,['D01']);assert.deepEqual(x.affectedDomains,['D01','D02']);});
test('established important conditions cannot be sacrificed behind a target fraction',()=>{const p=problem();p.target={importantNumerator:1,importantDenominator:2,status:'AUTHOR_POLICY_NOT_VALIDATED'};p.factDefinitions.push({id:'extraGood',kind:'COORDINATION',owner:'B',domain:'D02'});p.snapshot.values.extraGood='T';p.requirements.push({id:'extraGood',domain:'D02',direction:'BOTH',tier:'IMPORTANT',predicate:f('extraGood')});p.changes[0].effects.extraGood='F';const x=search(p);assert.equal(x.plans.length,0);assert.ok(x.rejected.some(r=>r.reason==='REGRESSES_ESTABLISHED_CONDITION'));});

test('skill threshold consumes ordinal possible levels, not an average',()=>{assert.equal(skillAtLeast([2,3],2),'T');assert.equal(skillAtLeast([1,2],2),'U');assert.equal(skillAtLeast([0,1],2),'F');assert.equal(skillAtLeast([0,1,2,3],2),'U');});
test('inconsistent ordinal level set cannot masquerade as sufficient skill',()=>assert.throws(()=>skillAtLeast([],2),/INVALID_ORDINAL/));
test('v02 level state bridges explicitly to a threshold predicate',()=>{const s=resolveLevels(['MET','MET','UNRESOLVED']);assert.deepEqual(s.possibleLevels,[2,3]);assert.equal(skillAtLeast(s.possibleLevels,2),'T');});
test('known empty set differs from missing set',()=>{assert.equal(intersectSets([],['x']).status,'F');assert.equal(intersectSets(null,['x']).status,'U');});
test('set intersection keeps actual alternatives, no distance between categories',()=>assert.deepEqual(intersectSets(['text','voice','text'],['text']),{status:'T',common:['text']}));
const interval=(l,u,lc=true,uc=true,unit='minute',period='specified-date')=>({lower:l,upper:u,lowerClosed:lc,upperClosed:uc,unit,period});
test('closed touching intervals have a point in common',()=>{const x=intersectIntervals(interval(1,2),interval(2,3));assert.equal(x.status,'T');assert.equal(x.interval.lower,2);assert.equal(x.interval.upper,2);});
test('open touching intervals do not overlap',()=>assert.equal(intersectIntervals(interval(1,2,true,false),interval(2,3)).status,'F'));
test('units are not silently converted',()=>assert.equal(intersectIntervals(interval(1,2),interval(1,2,true,true,'hour')).reason,'INCOMPARABLE'));
test('periods are not silently combined',()=>assert.equal(intersectIntervals(interval(1,2),interval(1,2,true,true,'minute','other-date')).reason,'INCOMPARABLE'));
test('empty half-open point interval remains empty',()=>assert.equal(intersectIntervals(interval(2,2,false,true),interval(1,3)).status,'F'));
test('missing interval remains unknown',()=>assert.equal(intersectIntervals(null,interval(1,2)).status,'U'));

test('certificate is tied to source and permission revisions and context',()=>{const p=problem(),plan=search(p).plans[0];assert.equal(isCertificateCurrent(plan,p.snapshot,p.publicationId),true);for(const mutate of [s=>s.revision++,s=>s.permissionRevision++,s=>s.context='newPair',s=>s.gate='UNAVAILABLE']){const q=clone(p.snapshot);mutate(q);assert.equal(isCertificateCurrent(plan,q,p.publicationId),false);}assert.equal(isCertificateCurrent(plan,p.snapshot,'other-version'),false);});
test('certificate explicitly denies a causal forecast and current score gain',()=>{const c=search(problem()).plans[0].certificate;assert.equal(c.isCausalForecast,false);assert.equal(c.changesCurrentScore,false);});
test('Pareto costs do not hide a high burden on either participant',()=>{const base=search(problem()).plans[0];const a={...base,actionIds:['a'],costs:{A_minutes:100,B_minutes:0}},b={...base,actionIds:['b'],costs:{A_minutes:0,B_minutes:100}},c={...base,actionIds:['c'],costs:{A_minutes:100,B_minutes:100}};assert.deepEqual(paretoPlans([a,b,c],['A_minutes','B_minutes']).map(x=>x.actionIds[0]),['a','b']);});
const card=(id,a,b,basisId='same-basis',lane='CURRENT_SUPPORTED')=>({id,a,b,basisId,lane});
test('asymmetric gain does not dominate mutual moderate alignment',()=>assert.equal(definitelyDominates(card('x',[10,10],[1,1]),card('y',[7,7],[7,7])),false));
test('known advantage in both directions supports partial ordering',()=>assert.equal(definitelyDominates(card('x',[8,8],[8,8]),card('y',[7,7],[7,7])),true));
test('missingness bounds do not become a point score',()=>{const x=card('x',[0,10],[0,10]),y=card('y',[7,7],[7,7]);assert.equal(definitelyDominates(x,y),false);assert.equal(definitelyDominates(y,x),false);});
test('different comparison basis means incomparable, not zero or worse',()=>assert.equal(definitelyDominates(card('x',[9,9],[9,9],'basis1'),card('y',[3,3],[3,3],'basis2')),false));
test('conditional potential cannot compete as current alignment',()=>assert.equal(definitelyDominates(card('x',[10,10],[10,10],'same','CONDITIONAL_OPTION'),card('y',[8,8],[8,8],'same','CURRENT_SUPPORTED')),false));
test('condition counts are labelled, not romantic success percentages',()=>{const p=problem();p.snapshot.values.BfullCycle='T';const x=observedConditionSummary(run(p),'A_cooks_B_shops');assert.equal(x.meaning,'COUNTS_OF_SELECTED_IMPORTANT_CONDITIONS_NOT_PROBABILITY');});

const confirmation=actor=>({actor,agreementRevision:1,contentHash:'same-content',decision:'T'});
const agreement=()=>({id:'ag',pairId:'p',revision:1,contentHash:'same-content',kind:'ORDINARY_TASK',confirmations:[confirmation('A'),confirmation('B')],revoked:false});
test('agreement requires two matching version confirmations',()=>assert.equal(agreementStatus(agreement(),'p'),'ACTIVE'));
test('one confirmation is not a shared agreement',()=>{const a=agreement();a.confirmations.pop();assert.equal(agreementStatus(a,'p'),'NEEDS_TWO_CONFIRMATIONS');});
test('old confirmation cannot ratify changed terms',()=>{const a=agreement();a.revision=2;assert.equal(agreementStatus(a,'p'),'NEEDS_TWO_CONFIRMATIONS');});
test('equal revision but different content cannot be assumed agreed',()=>{const a=agreement();a.confirmations[0].contentHash='different';assert.equal(agreementStatus(a,'p'),'NEEDS_TWO_CONFIRMATIONS');});
test('intimate consent is not a performance debt',()=>{const a=agreement();a.kind='INTIMATE_ACT';assert.equal(agreementStatus(a,'p'),'NO_OBLIGATION_TO_CONSENT');assert.equal(classifyAgreement({kind:'INTIMATE_ACT'}),'OUT_OF_SCOPE_NO_OBLIGATION_TO_CONSENT');});
test('revoked agreement is not active',()=>{const a=agreement();a.revoked=true;assert.equal(agreementStatus(a,'p'),'REVOKED');});
test('new pair cannot inherit prior agreement',()=>assert.equal(agreementStatus(agreement(),'new-pair'),'WRONG_PAIR'));
const report=(actor,value,shared=true)=>({actor,value,shared,pairId:'p',period:'week1',metricId:'load',scaleVersion:'authored-v1'});
test('one dissatisfied report cannot disappear in averaging',()=>assert.deepEqual(comparePairReports(report('A','GOOD'),report('B','NEEDS_CHANGE'),'p'),{status:'AT_LEAST_ONE_REQUESTS_CHANGE',a:'GOOD',b:'NEEDS_CHANGE'}));
test('private partner report does not influence shared psychological output',()=>{const a=report('A','GOOD');assert.deepEqual(comparePairReports(a,report('B','NEEDS_CHANGE',false),'p'),comparePairReports(a,report('B','GOOD',false),'p'));});
test('different periods cannot be merged',()=>{const b=report('B','GOOD');b.period='week2';assert.equal(comparePairReports(report('A','GOOD'),b,'p').status,'INCOMPARABLE');});
test('trend preserves individual source and only category ordering',()=>{assert.equal(ordinalReportTrend(report('A','ACCEPTABLE'),{...report('A','GOOD'),period:'week2'}),'IMPROVED_REPORTED_CATEGORY');assert.equal(ordinalReportTrend(report('A','GOOD'),report('B','GOOD')),'INCOMPARABLE');});

test('property: all 16 known four-condition states match exact conjunction',()=>{for(let mask=0;mask<16;mask++){const p=problem();const keys=['sameParenthood','sameFormat','BoffersShopping','BfullCycle'];keys.forEach((k,i)=>{p.snapshot.values[k]=(mask&(1<<i))?'T':'F';});assert.equal(run(p).samePlanWorksAcrossWorlds,mask===15);}});
test('property: uncertainty bounds contain every completion without optimistic conjunction',()=>{for(const a of ['T','F','U'])for(const b of ['T','F','U']){const p=problem();p.snapshot.values.BfullCycle=a;p.snapshot.values.BoffersShopping=b;const x=run(p);assert.equal(x.samePlanWorksAcrossWorlds,a==='T'&&b==='T');const possible=a!=='F'&&b!=='F';assert.equal(x.plans[0].possibleTarget,possible);}});
test('property: resource feasibility obeys joint integer boundary over all tested budgets',()=>{for(let cap=250;cap<=290;cap++){const p=problem();p.resources[1].capacity=cap;assert.equal(search(p).plans.length>0,cap>=270);}});
test('property: mutually exclusive plans never establish a universal witness without resolving unknown',()=>{const p=worldDependent();for(const value of ['T','F','U']){p.snapshot.values.unknownDay=value;assert.equal(run(p).samePlanWorksAcrossWorlds,value!=='U');}});

test('swapping participant labels preserves feasibility and swaps directional counts',()=>{const p=problem();p.snapshot.values.BfullCycle='T';const before=run(p);const q=clone(p);const swap=x=>x==='A'?'B':x==='B'?'A':x;q.factDefinitions.forEach(x=>x.owner=swap(x.owner));q.resources.forEach(x=>x.owner=swap(x.owner));q.requirements.forEach(x=>x.direction=x.direction==='A_FROM_B'?'B_FROM_A':x.direction==='B_FROM_A'?'A_FROM_B':'BOTH');q.changes.forEach(x=>{x.owners=x.owners.map(swap);x.willingness={A:x.willingness.B,B:x.willingness.A};});const after=run(q);assert.equal(after.status,before.status);assert.deepEqual(after.plans[0].a,before.plans[0].b);assert.deepEqual(after.plans[0].b,before.plans[0].a);});
test('principled mismatch visibility is not automatic contact permission',()=>{const p=problem();p.snapshot.values.sameParenthood='F';const x=search(p);assert.equal(laneFor(x),'DECLARED_DIFFERENCE');assert.equal(Object.hasOwn(x,'contactGranted'),false);});
test('one-domain route is a sufficient model route, not proof of one real psychological cause',()=>{const x=search(problem()).plans[0];assert.equal(x.certificate.isCausalForecast,false);assert.deepEqual(x.changedDomains,['D01']);assert.equal(Object.hasOwn(x,'onlyRealProblem'),false);});
test('current mismatch remains in current evaluation after finding potential',()=>{const x=search(problem());assert.equal(x.current.plans[0].requirementStatus.A_need_shopping_cycle,'F');assert.equal(x.plans[0].after.plans[0].requirementStatus.A_need_shopping_cycle,'T');});
test('all unmeasured conditions yield unknown, never a perfect sparse-profile score',()=>{const p=problem();Object.keys(p.snapshot.values).forEach(k=>{if(k!=='always')p.snapshot.values[k]='U';});const x=run(p);assert.equal(x.status,'NEEDS_CLARIFICATION');assert.equal(x.samePlanWorksAcrossWorlds,false);assert.equal(x.plans[0].a.matchedLower,0);assert.equal(x.plans[0].a.matchedUpper,x.plans[0].a.total);});
test('optional interests alone cannot yield a vacuous mutual target',()=>{const p=problem();p.requirements.forEach(r=>r.tier='PREFERENCE');assert.throws(()=>parseProblem(p),/EMPTY_TARGET_FOR_PARTICIPANT/);});
test('one-sided target cannot claim mutual compatibility',()=>{const p=problem();p.requirements.forEach(r=>r.direction='A_FROM_B');assert.throws(()=>parseProblem(p),/EMPTY_TARGET_FOR_PARTICIPANT/);});
