import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import ModeAwareProfileOverview from '@/components/profile/ModeAwareProfileOverview';
import { createEmptyProfileSummary, normalizeProfileSummary } from '@/client/viewmodels/profile.viewmodels';
import { composeAssessmentSources, type AssessmentCompositionSource } from '@/domain/assessment/sources';
import { getAssessmentPublication } from '@/domain/assessment/publication';
import { toAssessmentItemDTO } from '@/lib/dto/assessment.dto';
import { AssessmentResponseForm } from '@/features/assessments/AssessmentFormPage';
import { getUnavailableAssessmentSkills } from '@/domain/assessment/profile';

const publication = getAssessmentPublication('com-s02-application-beta')!;
const source: AssessmentCompositionSource = { subjectId: 'ui-beta-owner', sourceId: 'ui-beta-source', revision: 1, generation: 0, period: { id: 'august', startsAt: '2026-08-01T00:00:00.000Z', endsAt: '2026-08-29T00:00:00.000Z' }, publication, finalizedAt: '2026-08-29T01:00:00.000Z', contextIdentity: 'INDIVIDUAL', pairUse: false, matchingUse: false, permissionRevision: 0,
  answers: publication.items.map((item, index) => ({ itemId: item.id, presentationId: `receipt-${index}`, phase: 'BASELINE', revision: index + 1, recordedAt: '2026-08-29T00:00:00.000Z', response: { kind: 'FACTS', values: Object.fromEntries(item.fields.map(field => [field.id, field.id.startsWith('NEG.AGR.01.') && index === 1 && !field.id.endsWith('.eligible') ? null : true])), episode: { observedAt: '2026-08-10T00:00:00.000Z' } } })) };
const snapshot = composeAssessmentSources([source], { purpose: 'OWNER', sourceSetRevision: 1, now: new Date('2026-09-10') })!;
const summary = createEmptyProfileSummary(); summary.user.id = source.subjectId; summary.user.avatarUrl = '/synthetic.png'; summary.assessments = { version: 'assessment-profile-v1', status: 'READY', snapshot, unavailableSkills: getUnavailableAssessmentSkills() };
const normalized = normalizeProfileSummary(summary);
assert.deepEqual(normalized.assessments, summary.assessments);
const html = renderToStaticMarkup(React.createElement(ModeAwareProfileOverview, { summary: normalized }));
assert.match(html, /data-skill-id="COM.S02"/);
assert.match(html, /История описанных проявлений/);
assert.match(html, /от −4\/4 до −3\/4/);
assert.match(html, /Последнее наблюдение: 10\.08\.2026/);
assert.match(html, /Эти сведения остаются личными/);
assert.match(html, /Критерий уровня 1/);
assert.equal((html.match(/data-unavailable-skill-id=/g) ?? []).length, 51);
assert.match(html, /авторские определения, а не ваши измеренные уровни/);
const inconsistent = structuredClone(summary);
inconsistent.assessments!.snapshot!.skills[0].K = { ...inconsistent.assessments!.snapshot!.skills[0].K, status: 'INCONSISTENT', possibleLevels: [] };
assert.match(renderToStaticMarkup(React.createElement(ModeAwareProfileOverview, { summary: normalizeProfileSummary(inconsistent) })), /Сведения не согласуются: уровень не установлен/);
const rootId = 'ui-known-episode';
const prior = source.answers[0].response;
assert.equal(prior.kind, 'FACTS');
if (prior.kind !== 'FACTS') throw new Error('FACTS_TEST_FIXTURE_REQUIRED');
const form = renderToStaticMarkup(React.createElement(AssessmentResponseForm, { presentation: { presentationId: 'issued-ui', item: toAssessmentItemDTO(publication.items[1]), phase: 'BASELINE', hint: null }, previous: { ...prior, episode: { observedAt: '2026-08-10T00:00:00.000Z', sameEpisodeRootId: rootId } }, period: source.period, requiresEpisode: true, knownEpisodes: [{ rootId, label: 'Ранее описанная просьба', observedAt: '2026-08-10T00:00:00.000Z', publicationTitle: publication.title }], busy: false, onSave: async () => true, onHint: () => undefined }));
assert.match(form, /Это отдельный эпизод или уже описанный/);
assert.match(form, /value="ui-known-episode" selected=""/);
assert.match(form, /Повтор не увеличивает число эпизодов/);
assert.match(form, /type="datetime-local"/);
assert.match(form, /Ни один вариант не подходит/);
process.stdout.write(`${JSON.stringify({ suite: 'beta-content-profile-ui', status: 'passed', checks: 15, scope: 'ACTUAL_NORMALIZER_AND_COMPONENT_SSR_NOT_BROWSER', cases: [{ ids: ['BETA-032'], assertion: 'normalizer and actual profile component preserve COM negative bounds / dated history / null / inconsistent' }, { ids: ['BETA-017'], assertion: 'normalizer and actual owner component retain all51 unavailable definitions without measured levels' }, { ids: ['BETA-023', 'BETA-033', 'BETA-034'], assertion: 'actual response component renders selected owner episode reference and missing choices' }] })}\n`);
