'use client';
import { useState } from 'react';
import type { AssessmentComparisonDTO } from '@/lib/dto/assessmentComparison.dto';
import type { AssessmentPairDTO } from '@/lib/dto/assessmentPair.dto';
import { useAssessmentPair } from '@/client/hooks/useAssessmentPair';
import { confirmAppNavigation, useUnsavedChanges } from '@/client/hooks/useUnsavedChanges';

const labels = { NEEDS_CHANGE: 'Нужно изменить нагрузку', ACCEPTABLE: 'Нагрузка приемлема', GOOD: 'Нагрузка подходит хорошо' } as const;
type Category = keyof typeof labels;
const date = (value: string) => new Date(value).toLocaleDateString('ru-RU', { timeZone: 'UTC' });
export function ReportForm({ previous, busy, save, subject = 'LOAD' }: { subject?: 'LOAD' | 'AGREEMENT'; previous?: AssessmentPairDTO['reports'][number]; busy: boolean; save: (category: Category | null, shared: boolean) => Promise<boolean> }) {
  const [category, setCategory] = useState<Category | null>(previous?.own ?? null);
  const [chosen, setChosen] = useState(previous?.ownRecorded ?? false);
  const [shared, setShared] = useState(previous?.ownShared ?? false);
  const [dirty, setDirty] = useState(false);
  useUnsavedChanges(dirty, busy);
  return <form className="app-panel-soft p-4 space-y-3" onSubmit={event => { event.preventDefault(); if (chosen) void save(category, shared).then(ok => { if (ok) setDirty(false); }); }}><fieldset disabled={busy}><legend className="font-medium">{subject === 'AGREEMENT' ? 'Мой отдельный отчёт о приемлемости договорённости' : 'Мой отдельный отчёт о приемлемости нагрузки'}</legend>{[...Object.entries(subject === 'AGREEMENT' ? { NEEDS_CHANGE: 'Мне нужно изменить договорённость', ACCEPTABLE: 'Договорённость приемлема', GOOD: 'Договорённость подходит хорошо' } : labels).map(([id, label]) => ({ id: id as Category | null, label })), { id: null, label: 'Пока не могу оценить' }].map(option => <label key={option.id ?? 'unknown'} className="min-h-11 flex items-center gap-3"><input type="radio" name="pair-load-report" checked={chosen && category === option.id} onChange={() => { setCategory(option.id); setChosen(true); setDirty(true); }} />{option.label}</label>)}</fieldset><label className="min-h-11 flex items-start gap-3"><input type="checkbox" disabled={busy} checked={shared} onChange={event => { setShared(event.target.checked); setDirty(true); }} /><span>Разрешаю показать этот отчёт в общем представлении пары. Закрытый отчёт не раскрывает даже направление оценки.</span></label><p role="status">{busy ? 'Сохраняем отчёт…' : dirty ? 'Отчёт ещё не сохранён.' : previous?.ownRecorded ? 'Показан ваш сохранённый отчёт.' : 'Оценка заранее не выбрана.'}</p><button className="app-btn-primary" disabled={busy || !chosen}>Сохранить мой отчёт</button></form>;
}
export default function AssessmentPairPanel({ ownerId, comparison }: { ownerId: string; comparison: AssessmentComparisonDTO }) {
  const { data, error, busy, saved, mutate, reload } = useAssessmentPair(ownerId);
  const [plan, setPlan] = useState('');
  const [confirmation, setConfirmation] = useState<number | null>(null);
  const [periodId, setPeriodId] = useState('');
  const currentAvailable = comparison.current?.status === 'TARGET_SUPPORTED' && comparison.current.completeness === 'COMPLETE_WITHIN_LIMITS';
  const scenarios = comparison.scenarios.filter(scenario => scenario.status === 'TARGET_SUPPORTED' && scenario.completeness === 'COMPLETE_WITHIN_LIMITS' && scenario.baseRevision === comparison.current?.revision);
  const selectedValid = plan === 'CURRENT' ? currentAvailable : scenarios.some(scenario => scenario.id === plan);
  const ownConfirmed = data?.agreement && data.myRole ? data.agreement.confirmations[data.myRole] : false;
  const selectedPeriod = data?.periods.find(period => period.id === periodId);
  return <section className="space-y-4" aria-label="Договорённость и два отчёта пары">
    <h2 className="text-xl font-semibold">Добровольная бытовая договорённость</h2>
    <p>План станет действующей договорённостью только после двух независимых подтверждений одного содержания. Подтверждение, выполнение задачи и критерий навыка — разные события.</p>
    {error && <div role="alert" className="app-panel p-4"><p>{error}</p><button className="app-btn-secondary" disabled={busy} onClick={() => { if (confirmAppNavigation()) void reload(); }}>Обновить договорённость</button></div>}{!data && !error && <p role="status">Проверяем действующий контекст пары…</p>}{saved && <p role="status">Изменение подтверждено сервером.</p>}
    {data && <>
      {data.availability === 'UNAVAILABLE' && <p>Для общей договорённости пока нет доступного контекста. Нужны действующая пара и отдельные разрешения обоих участников на использование измерительных и прямых ответов в паре.</p>}
      {data.availability === 'AVAILABLE' && <div className="app-panel p-4 space-y-3"><label className="block"><span>Выберите основу конкретного предложения</span><select className="app-input block w-full" value={plan} disabled={busy} onChange={event => setPlan(event.target.value)}><option value="">Основа пока не выбрана</option>{currentAvailable && <option value="CURRENT">Поддержанный текущий план</option>}{scenarios.map((scenario, index) => <option key={scenario.id} value={scenario.id}>Условный вариант {index + 1}: с явно сохранёнными допущениями</option>)}</select></label><p className="app-muted">Условные предпосылки сохраняются в тексте. Само предложение не означает, что навык уже изменился.</p><button className="app-btn-primary" disabled={busy || !selectedValid} onClick={() => { if (confirmAppNavigation()) { setConfirmation(null); void mutate({ action: data.agreement ? 'revise' : 'propose', scenarioId: plan === 'CURRENT' ? null : plan, expectedRevision: data.revision }); } }}>{data.agreement ? 'Предложить новую версию содержания' : 'Предложить договорённость'}</button></div>}
      {data.agreement && <article className="app-panel p-4 space-y-4"><h3 className="font-semibold text-lg">{data.agreement.title} · версия {data.agreement.contentRevision}</h3><p>{data.agreement.content}</p>{data.agreement.assumptions.length > 0 && <ul className="list-disc pl-5">{data.agreement.assumptions.map(value => <li key={value}>{value}</li>)}</ul>}<p className="font-medium">{data.agreement.status === 'ACTIVE' ? 'Оба участника подтвердили эту версию.' : data.agreement.status === 'REVOKED' ? 'Участие отозвано; договорённость не активна.' : 'Предложение ожидает двух независимых подтверждений.'}</p><dl className="flex flex-wrap gap-6"><div><dt>Участник A</dt><dd>{data.agreement.confirmations.A ? 'Подтвердил' : 'Подтверждения нет'}</dd></div><div><dt>Участник B</dt><dd>{data.agreement.confirmations.B ? 'Подтвердил' : 'Подтверждения нет'}</dd></div></dl><p>Принятие договорённости не повышает текущий навык.</p>{data.agreement.status !== 'REVOKED' && !ownConfirmed && <><label className="min-h-11 flex items-start gap-3"><input type="checkbox" disabled={busy} checked={confirmation === data.agreement.contentRevision} onChange={event => setConfirmation(event.target.checked ? data.agreement!.contentRevision : null)} /><span>Я прочитал именно эту версию и добровольно подтверждаю только своё участие.</span></label><button className="app-btn-primary" disabled={busy || confirmation !== data.agreement.contentRevision} onClick={() => void mutate({ action: 'confirm', expectedRevision: data.revision, expectedContentRevision: data.agreement!.contentRevision })}>Подтвердить моё участие в этой версии</button></>}<div className="flex flex-wrap gap-3"><button className="app-btn-secondary" disabled={busy} onClick={() => { if (confirmAppNavigation()) void reload(); }}>Проверить подтверждение второго участника</button>{data.agreement.status !== 'REVOKED' && <button className="app-btn-secondary" disabled={busy} onClick={() => void mutate({ action: 'revoke', expectedRevision: data.revision })}>Отозвать моё участие</button>}</div></article>}
      {data.agreement?.status === 'ACTIVE' && <section className="space-y-3"><h3 className="text-lg font-semibold">Отдельные отчёты о нагрузке</h3><label className="block"><span>Период отчёта (UTC)</span><select className="app-input block w-full" value={periodId} disabled={busy} onChange={event => { if (confirmAppNavigation()) setPeriodId(event.target.value); }}><option value="">Выберите конкретный период</option>{data.periods.map(period => <option key={period.id} value={period.id}>{period.label}: {date(period.window.start)} — {date(new Date(Date.parse(period.window.end) - 1).toISOString())}</option>)}</select></label>{selectedPeriod && <ReportForm key={`${ownerId}:${periodId}:${data.revision}`} previous={data.reports.find(report => report.periodId === periodId)} busy={busy} save={(category, shared) => mutate({ action: 'report', periodId, category, shared, expectedRevision: data.revision })} />}</section>}
      {data.agreement?.status === 'ACTIVE' && <section className="app-panel p-4 space-y-3"><h3 className="font-semibold">Новые отдельные наблюдения после попытки</h3><p>Откроется новое прохождение для описания других бытовых эпизодов. Принятая договорённость и завершённая попытка сами по себе не повышают навык. Пересчёт произойдёт только после сохранения подходящих новых наблюдений.</p><button className="app-btn-primary" disabled={busy} onClick={() => { if (confirmAppNavigation()) void mutate({ action: 'observe', expectedRevision: data.revision }).then(ok => { if (ok) { window.dispatchEvent(new Event('assessment-source-changed')); window.dispatchEvent(new Event('profile-measurements-changed')); } }); }}>Описать новые отдельные эпизоды</button></section>}{data.reports.map(report => <article className="app-panel-soft p-4 space-y-3" key={report.periodId}><h3 className="font-semibold">{data.periods.find(period => period.id === report.periodId)?.label ?? 'Отчёт за отдельный период'}</h3><p>Ваш отдельный взгляд: {report.own ? labels[report.own] : 'неизвестно'}. {report.ownShared ? 'Разрешён для общего вида.' : 'Не разрешён для общего вида.'}</p><dl className="space-y-2"><div><dt>Общий вид: участник A</dt><dd>{report.A ? labels[report.A] : 'нет доступного значения'}</dd></div><div><dt>Общий вид: участник B</dt><dd>{report.B ? labels[report.B] : 'нет доступного значения'}</dd></div></dl><p>{report.status === 'AT_LEAST_ONE_REQUESTS_CHANGE' ? 'Как минимум один участник просит изменить нагрузку. Эта потребность не исчезает из-за оценки второго.' : report.status === 'SHARED_DATA_INCOMPLETE' ? 'Общих данных недостаточно. Направление закрытого отчёта не раскрывается.' : report.status === 'DIFFERENT_REPORTED_CATEGORIES' ? 'Два разных взгляда сохранены раздельно.' : report.status === 'INCOMPARABLE' ? 'Эти отчёты нельзя сопоставить.' : 'В этом периоде сообщены одинаковые категории.'}</p><p className="app-muted">Динамика вашего отчёта: {report.ownTrend === 'IMPROVED_REPORTED_CATEGORY' ? 'более приемлемая категория' : report.ownTrend === 'LOWER_REPORTED_CATEGORY' ? 'менее приемлемая категория' : report.ownTrend === 'SAME_REPORTED_CATEGORY' ? 'категория не изменилась' : report.ownTrend === 'INCOMPARABLE' ? 'периоды несопоставимы' : 'неизвестна'}. Это не изменение личности другого.</p>{report.ownShared && <button className="app-btn-secondary" disabled={busy} onClick={() => void mutate({ action: 'revoke-report', periodId: report.periodId, expectedRevision: data.revision })}>Закрыть мой отчёт от общего просмотра</button>}</article>)}
    </>}
  </section>;
}
