'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import BackBar from '@/components/ui/BackBar';
import { assessmentBetaApi } from '@/client/api/assessmentBeta';
import { useAssessmentResource } from '@/client/hooks/useAssessmentResource';
import { useUnsavedChanges } from '@/client/hooks/useUnsavedChanges';
import { betaDirectPlanSchema, type BetaDirectPlan } from '@/lib/dto/assessmentBeta.dto';
import { localTimeToInstant, type BetaInterval } from '@/lib/dto/assessmentClient.dto';

const offers = [{ value: 'COOKING', label: 'Приготовление еды' }, { value: 'SHOPPING', label: 'Покупки' }, { value: 'PAUSE_RETURN', label: 'Организация паузы и возвращения' }] as const;
const channels = [{ value: 'TEXT', label: 'Текст' }, { value: 'VOICE', label: 'Голос' }, { value: 'VIDEO', label: 'Видео' }, { value: 'IN_PERSON', label: 'Лично' }] as const;
const notices = [{ value: 'MESSAGE', label: 'Сообщение' }, { value: 'VOICE', label: 'Сказать голосом' }, { value: 'SIGNAL', label: 'Согласованный сигнал' }] as const;
function Select<T extends string>({ label, value, choices, change }: { label: string; value: T | null; choices: readonly { value: T; label: string }[]; change: (value: T | null) => void }) {
  return <label className="block">{label}<select className="app-input block w-full mt-1" value={value ?? ''} onChange={event => change(choices.find(choice => choice.value === event.target.value)?.value ?? null)}><option value="">Пока не знаю / не указано</option>{choices.map(choice => <option key={choice.value} value={choice.value}>{choice.label}</option>)}</select></label>;
}
function SetInput<T extends string>({ label, value, choices, change }: { label: string; value: T[] | null; choices: readonly { value: T; label: string }[]; change: (value: T[] | null) => void }) {
  return <fieldset className="app-panel-soft p-3"><legend>{label}</legend><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={value !== null} onChange={event => change(event.target.checked ? [] : null)} />Могу указать допустимые варианты</label>{value !== null && <><p className="app-muted text-sm">Если ничего не отмечено, ни один перечисленный вариант не подходит.</p>{choices.map(choice => <label key={choice.value} className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={value.includes(choice.value)} onChange={event => change(event.target.checked ? [...value, choice.value] : value.filter(item => item !== choice.value))} />{choice.label}</label>)}</>}</fieldset>;
}
function Tri({ label, value, change }: { label: string; value: boolean | null; change: (value: boolean | null) => void }) {
  return <Select label={label} value={value === null ? null : value ? 'YES' : 'NO'} choices={[{ value: 'YES', label: 'Да' }, { value: 'NO', label: 'Нет' }]} change={next => change(next === null ? null : next === 'YES')} />;
}
function Amount({ label, value, change, max = 80640 }: { label: string; value: number | null; change: (value: number | null) => void; max?: number }) {
  return <label className="block">{label}<input className="app-input block w-full mt-1" type="number" min={0} max={max} step={1} value={value ?? ''} onChange={event => change(event.target.value === '' ? null : Number(event.target.value))} /><span className="app-muted text-sm">Пустое поле означает неизвестность.</span></label>;
}
function localLabel(instant: string, timezone: string) {
  try { return new Intl.DateTimeFormat('ru-RU', { timeZone: timezone, dateStyle: 'short', timeStyle: 'short' }).format(new Date(instant)); } catch { return 'Проверьте часовой пояс'; }
}
function localDate(instant: string | undefined, timezone: string) {
  if (!instant) return '';
  const parts = new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date(instant));
  const part = (type: 'year' | 'month' | 'day') => parts.find(value => value.type === type)?.value ?? '';
  return `${part('year')}-${part('month')}-${part('day')}`;
}
function ValidationError({ message }: { message: string | null }) {
  const ref = useRef<HTMLParagraphElement>(null);
  useEffect(() => { if (message) ref.current?.focus(); }, [message]);
  return message ? <p ref={ref} tabIndex={-1} role="alert">{message}</p> : null;
}
function Windows({ label, intervals, timezone, change }: { label: string; intervals: BetaInterval[]; timezone: string; change: (values: BetaInterval[]) => void }) {
  const [start, setStart] = useState(''), [end, setEnd] = useState(''), [error, setError] = useState<string | null>(null);
  const add = () => { try {
    const startsAt = localTimeToInstant(start.slice(0, 10), start.slice(11), timezone), endsAt = localTimeToInstant(end.slice(0, 10), end.slice(11), timezone);
    if (Date.parse(endsAt) <= Date.parse(startsAt)) throw new Error();
    change([...intervals, { startsAt, endsAt }]); setStart(''); setEnd(''); setError(null);
  } catch { setError('Проверьте время и часовой пояс. Неоднозначное или отсутствующее местное время нужно указать иначе.'); } };
  return <fieldset className="app-panel-soft p-3 space-y-3"><legend className="font-semibold">{label}</legend><p className="app-muted text-sm">Местное время в выбранном часовом поясе. Начало включено, конец не включён.</p><ul className="space-y-2">{intervals.map((interval, index) => <li key={index} className="flex flex-wrap gap-3 items-center"><span>{localLabel(interval.startsAt, timezone)} — {localLabel(interval.endsAt, timezone)}</span><button className="app-btn-secondary" type="button" onClick={() => change(intervals.filter((_, row) => row !== index))}>Убрать окно {index + 1}</button></li>)}</ul><label className="block">Начало<input className="app-input block w-full" type="datetime-local" value={start} onChange={event => setStart(event.target.value)} /></label><label className="block">Конец<input className="app-input block w-full" type="datetime-local" value={end} onChange={event => setEnd(event.target.value)} /></label><button type="button" className="app-btn-secondary" disabled={!start || !end || intervals.length >= 32} onClick={add}>Добавить окно</button><ValidationError message={error} /></fieldset>;
}
function initialPlan(): BetaDirectPlan {
  return { templateId: 'DOM.S07', period: { startsAt: '', endsAt: '' }, timezone: 'UTC', calendarComplete: false, availableIntervals: [], alternativeIntervals: [], offer: null, acceptableOffers: null, idealOffer: null, excludedOffers: [], conditionImportance: 'MUST', requireAppliedCriterion: false, willingness: null, alternativeOffer: null, willingAlternative: null, resource: { unit: 'minute', lineageId: '', capacity: null, basis: 'TOTAL', ordinaryUse: 0 }, criterionAttemptMinutes: null, scheduleAttemptMinutes: null, organizationAttemptMinutes: null, willingCriterion: null, willingSchedule: null, provenance: 'USER_INPUT', disclosureVersion: 'beta-direct-predicate-v1', offeredChannel: null, alternativeChannel: null, acceptableChannels: null, conversationPrivacy: null, pauseReturn: null, personalTime: null };
}
const readConditions = async (signal: AbortSignal) => {
  const [direct, settings] = await Promise.all([assessmentBetaApi.direct(signal), assessmentBetaApi.settings(signal)]);
  return { direct, settings };
};
type Resource = ReturnType<typeof useAssessmentResource<Awaited<ReturnType<typeof readConditions>>>>;
function ConditionsForm({ resource }: { resource: Resource }) {
  const data = resource.data!;
  const [plan, setPlan] = useState<BetaDirectPlan>(data.direct.plan ?? initialPlan());
  const [start, setStart] = useState(() => localDate(data.direct.plan?.period.startsAt, plan.timezone)), [end, setEnd] = useState(() => localDate(data.direct.plan?.period.endsAt, plan.timezone));
  const [ordinary, setOrdinary] = useState(data.direct.plan ? String(data.direct.plan.resource.ordinaryUse) : '');
  const [dirty, setDirty] = useState(false), [error, setError] = useState<string | null>(null);
  const request = useRef<{ fingerprint: string; key: string } | null>(null);
  const lineage = useRef(data.direct.plan?.resource.lineageId ?? null);
  useUnsavedChanges(dirty, resource.busy);
  const update = <K extends keyof BetaDirectPlan>(key: K, value: BetaDirectPlan[K]) => { setPlan(previous => ({ ...previous, [key]: value })); setDirty(true); };
  const choices = offers.filter(option => plan.templateId === 'COM.S04' ? option.value === 'PAUSE_RETURN' : option.value !== 'PAUSE_RETURN');
  const pause = plan.pauseReturn ?? { notice: null, acceptableNotices: null, returnMinutes: null, acceptableReturnMinutes: null, allowRevision: null };
  return <form className="space-y-5" onSubmit={event => {
    event.preventDefault(); setError(null);
    if (ordinary === '') { setError('Укажите обычную нагрузку; если её нет, введите 0.'); return; }
    lineage.current ??= crypto.randomUUID();
    let period: BetaInterval;
    try { period = { startsAt: localTimeToInstant(start, '00:00', plan.timezone), endsAt: localTimeToInstant(end, '00:00', plan.timezone) }; } catch { setError('Укажите конечные даты и действующий часовой пояс.'); return; }
    const parsed = betaDirectPlanSchema.safeParse({ ...plan, period, resource: { ...plan.resource, lineageId: lineage.current, ordinaryUse: Number(ordinary) } });
    if (!parsed.success) { setError('Проверьте условия: период до 56 дней, окна внутри периода, допустимые целые минуты и отсутствие исключённых вариантов среди приемлемых.'); return; }
    const fingerprint = JSON.stringify(parsed.data); if (request.current?.fingerprint !== fingerprint) request.current = { fingerprint, key: crypto.randomUUID() };
    void resource.run(async (current, signal) => { await assessmentBetaApi.saveDirect({ action: 'save', plan: parsed.data, expectedRevision: current.direct.revision, viewerToken: current.direct.viewerToken, idempotencyKey: request.current!.key, discoveryOptIn: current.settings.settings.discovery, pairUse: current.settings.settings.pairSharing }, signal); }).then(ok => { if (ok) { setDirty(false); request.current = null; } });
  }}><fieldset disabled={resource.busy} className="space-y-5">
    <section className="app-panel p-4 space-y-3"><h2 className="text-xl font-semibold">Контекст и период</h2><label className="block">Что согласуем<select className="app-input block w-full" value={plan.templateId} onChange={event => { const value = event.target.value; if (value === 'DOM.S07' || value === 'COM.S04') { setPlan(previous => ({ ...previous, templateId: value, offer: null, idealOffer: null, alternativeOffer: null, acceptableOffers: null, excludedOffers: [] })); setDirty(true); } }}><option value="DOM.S07">Бытовая задача</option><option value="COM.S04">Пауза и возврат к разговору</option></select></label>
      <label className="block">Часовой пояс IANA<input className="app-input block w-full" value={plan.timezone} onChange={event => update('timezone', event.target.value)} placeholder="Например, Asia/Almaty" /></label>
      <div className="grid sm:grid-cols-2 gap-3"><label>Первый день<input className="app-input block w-full" required type="date" value={start} onChange={event => { setStart(event.target.value); setDirty(true); }} /></label><label>Конец периода (этот день не включён)<input className="app-input block w-full" required type="date" value={end} onChange={event => { setEnd(event.target.value); setDirty(true); }} /></label></div>
      <p className="app-muted text-sm">Период относится к будущему плану. Он не заменяет период прошлых наблюдений в анкете.</p>
    </section>
    <section className="app-panel p-4 space-y-4"><h2 className="text-xl font-semibold">Моё предложение и мои условия</h2><Select label="Предлагаю свою часть" value={plan.offer} choices={choices} change={value => update('offer', value)} /><Tri label="Готовность участвовать в этом предложении" value={plan.willingness} change={value => update('willingness', value)} /><SetInput label="Что мне подходит со стороны другого" value={plan.acceptableOffers} choices={choices} change={value => update('acceptableOffers', value)} /><Select label="Предпочтительный вариант" value={plan.idealOffer} choices={choices} change={value => update('idealOffer', value)} /><SetInput label="Что исключено" value={plan.excludedOffers} choices={choices} change={value => update('excludedOffers', value ?? [])} /><Select label="Значимость условия" value={plan.conditionImportance} choices={[{ value: 'MUST', label: 'Обязательно' }, { value: 'IMPORTANT', label: 'Важно' }, { value: 'PREFERENCE', label: 'Предпочтение' }]} change={value => { if (value) update('conditionImportance', value); }} /><label className="flex gap-3 min-h-11 items-start"><input className="mt-1" type="checkbox" checked={plan.requireAppliedCriterion} onChange={event => update('requireAppliedCriterion', event.target.checked)} /><span>Для этой конкретной задачи хочу учитывать допущенный критерий описанного применения. Если оснований недостаточно, он остаётся неизвестным.</span></label></section>
    {plan.templateId === 'COM.S04' && <section className="app-panel p-4 space-y-4"><h2 className="text-xl font-semibold">Способ разговора и возвращения</h2><Select label="Предлагаемый канал" value={plan.offeredChannel ?? null} choices={channels} change={value => update('offeredChannel', value)} /><SetInput label="Приемлемые для меня каналы" value={plan.acceptableChannels ?? null} choices={channels} change={value => update('acceptableChannels', value)} /><Select label="Предлагаемая обстановка" value={plan.conversationPrivacy?.offered ?? null} choices={[{ value: 'PRIVATE', label: 'Приватно' }, { value: 'PUBLIC', label: 'При других людях' }]} change={value => update('conversationPrivacy', { offered: value, required: plan.conversationPrivacy?.required ?? null })} /><Select label="Моё условие приватности" value={plan.conversationPrivacy?.required ?? null} choices={[{ value: 'PRIVATE', label: 'Только приватно' }, { value: 'EITHER', label: 'Оба варианта приемлемы' }]} change={value => update('conversationPrivacy', { offered: plan.conversationPrivacy?.offered ?? null, required: value })} /><Select label="Как я обозначу паузу" value={pause.notice} choices={notices} change={value => update('pauseReturn', { ...pause, notice: value })} /><SetInput label="Какое обозначение паузы мне понятно" value={pause.acceptableNotices} choices={notices} change={value => update('pauseReturn', { ...pause, acceptableNotices: value })} /><Amount label="Предлагаемый срок возвращения, минуты" max={10080} value={pause.returnMinutes} change={value => update('pauseReturn', { ...pause, returnMinutes: value })} /><div className="grid sm:grid-cols-2 gap-3"><Amount label="Приемлемый минимум, минуты" max={10080} value={pause.acceptableReturnMinutes?.min ?? null} change={value => update('pauseReturn', { ...pause, acceptableReturnMinutes: value === null ? null : { min: value, max: pause.acceptableReturnMinutes?.max ?? value } })} /><Amount label="Приемлемый максимум, минуты" max={10080} value={pause.acceptableReturnMinutes?.max ?? null} change={value => update('pauseReturn', { ...pause, acceptableReturnMinutes: value === null ? null : { min: pause.acceptableReturnMinutes?.min ?? value, max: value } })} /></div><Tri label="Готовность отдельно пересогласовать срок" value={pause.allowRevision} change={value => update('pauseReturn', { ...pause, allowRevision: value })} /><p className="app-muted">Предложение не подтверждает возвращение за другого. Небезопасный или нежелательный контакт можно прекратить.</p></section>}
    <section className="app-panel p-4 space-y-4"><h2 className="text-xl font-semibold">Ресурс в этом периоде</h2><Amount label="Доступное время, минуты" value={plan.resource.capacity} change={value => update('resource', { ...plan.resource, capacity: value })} /><Select label="Что означает указанное время" value={plan.resource.basis} choices={[{ value: 'TOTAL', label: 'Весь бюджет: обычная работа ещё не вычтена' }, { value: 'REMAINING_AFTER_ORDINARY', label: 'Остаток после обычной работы' }]} change={value => { if (value) update('resource', { ...plan.resource, basis: value }); }} /><label className="block">Обычная нагрузка этой задачи в том же периоде, минуты<input className="app-input block w-full" required type="number" min={0} max={80640} step={1} value={ordinary} onChange={event => { setOrdinary(event.target.value); setDirty(true); }} /><span className="app-muted text-sm">Для остатка нагрузка повторно не вычитается. Если нагрузки нет, укажите 0.</span></label>
      <details><summary>Мой отдельный резерв личного времени</summary><div className="space-y-3 mt-3"><Amount label="Минимум, минуты" value={plan.personalTime?.minMinutes ?? null} change={value => update('personalTime', value === null ? null : { minMinutes: value, maxMinutes: plan.personalTime?.maxMinutes ?? value, basis: plan.personalTime?.basis ?? 'INCLUDED_IN_CAPACITY' })} /><Amount label="Максимум, минуты" value={plan.personalTime?.maxMinutes ?? null} change={value => update('personalTime', value === null ? null : { minMinutes: plan.personalTime?.minMinutes ?? value, maxMinutes: value, basis: plan.personalTime?.basis ?? 'INCLUDED_IN_CAPACITY' })} /><Select label="Учёт резерва" value={plan.personalTime?.basis ?? null} choices={[{ value: 'INCLUDED_IN_CAPACITY', label: 'Нужно зарезервировать из указанного времени' }, { value: 'ALREADY_RESERVED', label: 'Уже зарезервировано, повторно не вычитать' }]} change={value => { if (value && plan.personalTime) update('personalTime', { ...plan.personalTime, basis: value }); }} /></div></details>
    </section>
    <Windows label="Мои доступные окна" intervals={plan.availableIntervals} timezone={plan.timezone} change={value => update('availableIntervals', value)} /><label className="flex gap-3 min-h-11 items-start"><input className="mt-1" type="checkbox" checked={plan.calendarComplete} onChange={event => update('calendarComplete', event.target.checked)} /><span>Это все доступные мне окна в выбранном периоде. Если не отмечено, календарь неполон и отсутствие пересечения остаётся неизвестным.</span></label>
    <details className="app-panel p-4"><summary className="font-semibold">Добровольные варианты для отдельного условного расчёта</summary><div className="space-y-4 mt-4"><p>Это допускаемые варианты, а не принятые обязательства и не достигнутый навык. Ваш отказ не меняется решателем.</p><Select label="Иной способ организации" value={plan.alternativeOffer} choices={choices} change={value => update('alternativeOffer', value)} /><Tri label="Готовность рассмотреть иной способ" value={plan.willingAlternative} change={value => update('willingAlternative', value)} />{plan.templateId === 'COM.S04' && <Select label="Другой допустимый для меня канал" value={plan.alternativeChannel ?? null} choices={channels} change={value => update('alternativeChannel', value)} />}<Tri label="Готовность рассмотреть работу над конкретным критерием" value={plan.willingCriterion} change={value => update('willingCriterion', value)} /><Amount label="Мой доступный ресурс для попытки, минуты (не срок освоения)" value={plan.criterionAttemptMinutes} change={value => update('criterionAttemptMinutes', value)} /><Amount label="Мой ресурс для иной организации, минуты" value={plan.organizationAttemptMinutes} change={value => update('organizationAttemptMinutes', value)} /><Tri label="Готовность рассмотреть другое время" value={plan.willingSchedule} change={value => update('willingSchedule', value)} /><Amount label="Мой ресурс для изменения расписания, минуты" value={plan.scheduleAttemptMinutes} change={value => update('scheduleAttemptMinutes', value)} /><Windows label="Альтернативные окна" intervals={plan.alternativeIntervals} timezone={plan.timezone} change={value => update('alternativeIntervals', value)} /></div></details>
    <p className="app-muted">Эти условия доступны по сохранённым настройкам: поиск {data.settings.settings.discovery ? 'включён' : 'выключен'}, использование в паре {data.settings.settings.pairSharing ? 'включено' : 'выключено'}. <Link className="underline" href="/profile/settings#assessment-settings">Изменить настройки</Link></p>
    <ValidationError message={error} /><button className="app-btn-primary" disabled={resource.busy}>{resource.busy ? 'Сохраняем…' : 'Сохранить мои условия'}</button>{dirty && <p role="status">Есть изменения, ещё не подтверждённые сервером.</p>}
  </fieldset></form>;
}
export default function AssessmentConditionsPage() {
  const resource = useAssessmentResource(readConditions);
  return <main className="app-shell-narrow py-5 space-y-5"><BackBar title="Мои условия" fallbackHref="/assessments" /><h1 className="text-2xl font-semibold">Что я предлагаю и что мне подходит</h1><p>Условия принадлежат вам. Способность не означает готовность, а бюджет периода не гарантирует свободного вечера.</p>{resource.error && <p role="alert">{resource.error}</p>}{resource.saved && <p role="status">Условия сохранены. Предыдущие зависимые расчёты требуют обновления.</p>}{!resource.data && <button className="app-btn-secondary" disabled={resource.busy} onClick={() => void resource.reload()}>{resource.busy ? 'Проверяем текущий аккаунт…' : 'Повторить загрузку'}</button>}{resource.data && <ConditionsForm key={resource.ownerId} resource={resource} />}<nav className="flex flex-wrap gap-3"><Link className="app-btn-secondary" href="/assessments/discovery">К знакомствам</Link><Link className="app-btn-secondary" href="/assessments/pair">К договорённостям пары</Link></nav></main>;
}
